### ISSUE TITLE
Expecting a doc available as a markdown file specifying the data schema design for a wallet/db storage 

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1054]
Currently, most data in a wallet (aka db storage, for example postgresql) are binary. It's really hard for people new to ACA-Py to figure out what real data is stored in the wallet. Without having this knowledge, it's then hard for us to design/develop controllers to handle necessary data that are not stored in the wallet, but have to be persisted to somewhere else (e.g. protocol execution).

**What is expect**: a doc to be available as a markdown file that gives the data schema design, what each data table is for plus some example data (non-binary data example) for clarification for a wallet. It should include multi-tenancy, as it's a fascinating feature in V0.6.0 and would be necessary for enterprise-level apps design.

**Comment by swcurran** [comment]
Some additional questions.  @andrewwhitehead -- could you take a shot at these in the context of the indy-wallet that is part of the Indy-SDK and Aries Askar:

1. if there are any detailed descriptions on this topic available anywhere?
2. what are the plaintext values for "name", "value" and "type"? 
3. how are secret keys designed in indy-sdk? 
4. I guess SHA256 is the encryption approach used, but does it used in indy-sdk or is it used by using Ursa?
5. the items table has a column called "key", is it used to store the encryption key for each row? 
6. why do other tables (i.e. metadata, tags_encrypted) not have this column?
7. what are the general purpose for the four tables (i.e. items, metadata, tag_encrypted and tags_plaintext)?

**Comment by ianco** [comment]
As far as I know there isn't documentation in the internals of the Indy wallet storage.  This document describes the high-level API which applies to all Indy wallets (sqlite, postgres, and any others):  https://github.com/hyperledger/indy-sdk/tree/master/docs/design/003-wallet-storage

Because the wallet is managed by Indy itself, the plug-in (sqlite, postgres, etc) just handles the read and write of the blob storage between the database and indy-sdk.  I agree it's a challenge to work with a "black box" database, but it is what it is.  You don't ever query the database directly, you query based on the api's provided by indy-sdk, which are documented in the above linked doc.

I believe that the metadata holds the symmetric keys that are used to encrypt data in the items and tags_encrypted table.  (tags_plaintext is not encrypted)  The data in metadata is encrypted based on your provided wallet key.  You can rotate your wallet key, which updates the metadata table, but afaik you can't update the symmetric keys that are used to encrypt the rest of the wallet data.

As mentioned, "metadata" holds the symmetric keys and I'm not sure what else.  "items" holds *all* the data basically (DID's, credential definitions, credentials, any non-secrets data, and whatever else).  "tags_*" stores any tags o the "items" records, which are used for searching (WQL) (since the data in "items" is completely encrypted and un-searchable).

I'm not sure about the encryption-related questions, there is some description in the doc I linked above, otherwise you'll need to dig into the rust code.

**Comment by yunxi-zhang** [comment]
Thanks for the info @ianco, i've viewed the article in the link you mentioned already. I still believe to have a proper documentation explaining the internal design of the wallet is helpful especially for enterprise/corporate-level systems. As there will be risks for corporates to use something that is a black box to them, especially when considering the db backup and recovery design. In addition, having a documentation can also lower the threshold for new comers to entering Indy world. @swcurran , you mentioned your team has been working on digging into the rust code in the community channel, do you have an ETC on this task?

**Comment by yunxi-zhang** [comment]
Hello @swcurran , is there any updates/progress on this ticket since my last comments?

**Comment by swcurran** [comment]
Nothing yet - sorry.  The information needs to go into the [aries-askar](https://github.com/hyperledger/aries-askar) repo, with a pointer from here to that repo.

Since the aries-askar design is based on that of the "indy-wallet" in the [indy-sdk](), here are some docs from the indy-sdk repo that might kickstart this effort:

- [Design - Wallet Storage](https://github.com/hyperledger/indy-sdk/tree/master/docs/design/003-wallet-storage)
- [Design - Wallet Export - Import](https://github.com/hyperledger/indy-sdk/tree/master/docs/design/009-wallet-export-import)
- [Design - Wallet Query Language](https://github.com/hyperledger/indy-sdk/tree/master/docs/design/011-wallet-query-language)
- [Wallet in "concepts" docs folder](https://github.com/hyperledger/indy-sdk/blob/master/docs/concepts/default-wallet.md)

@andrewwhitehead -- perhaps you can provide me with a summary of the Askar / Indy Wallet differences so that we can evolve these documents to be Askar-specific.

**Comment by swcurran** [comment]
Closing this issue in ACA-Py in expectation of the update in Askar.
