### ISSUE TITLE
jsonld compact/expand performance is atrocious

### ISSUE THREAD

**Issue by sklump** [hyperledger/aries-cloudagent-python#1109]
A compact or verify operation takes over a minute from my side. How can this be? Can anything be done?

The unit test suite, because it runs these operations several times, spends over half its run on `aries_cloudagent/messaging/jsonld/tests/test_credential.py`. Now that jsonld is exposed in the admin API, I believe many people will experience http timeouts on its operations.

**Comment by andrewwhitehead** [comment]
Can you narrow it down to specific statements that are taking a long time?

**Comment by swcurran** [comment]
@TimoGlastra -- do you think this might be JSON-LD context loading?

**Comment by TimoGlastra** [comment]
Could be. It's not using local context so that may take a while. Especially if the documents are not cached after the first run

Related to https://github.com/hyperledger/aries-cloudagent-python/issues/920

We're using local context for our tests, so we should probably refactor the JSONLD routes to do the same. Should be easy once our PR is merged

**Comment by sklump** [comment]
@swcurran any compact() or verify() operation in the json-ld 3rd party library takes about a minute and change.
