### ISSUE TITLE
Provide list of ursa components used and code that calls ursa and other cryptographic libraries in preparation for an audit

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1126]
Please provide for aries-askar and ACA-Py:

- A list of Ursa subcomponents used in the two products.
- A list of any other cryptographic libraries called in the two products.
- A list of pointers into the code of aries-askar and ACA-Py where the components of the previous two lists are used.
   - Ideally, include a brief (one-liner) summary of what the code does, if needed.

Probably best to have the pointers to the code go to a commit, so that they stay stable.

This data will be used as input into an assessment of the cryptography of Ursa, ACA-Py and aries-askar.

**Comment by swcurran** [comment]
Andrew -- what we talked about the other day, but with the some additional information needed.

**Comment by swcurran** [comment]
Would it take long to do the indy-sdk?  I don't have anyone doing that right now.  But if this is a lot for you, I can find someone else. If it will be quick for you, please do.

**Comment by andrewwhitehead** [comment]
It looks like `indy-sdk` uses mostly the same parts:

- Essentially all of `ursa::cl` along with `ursa::bn::BigNumber` (OpenSSL), to implement Anoncreds.
- `ursa::bls::{Bls, Generator, MultiSignature, VerKey}` to verify transaction state proofs
   - indy-sdk also uses `bls::SignKey` to create a signature, but only in tests.
- It looks like it uses use `ursa::keys::PublicKey` and `ursa::signatures::ed25519::Ed25519Sha512` but only in one test. Otherwise it uses libsodium/sodiumoxide to handle the ed25519 key operations.

`indy-node` via `indy-plenum` also depends on the Ursa BLS support, signing and verification of multi-signatures.

**Comment by swcurran** [comment]
Excellent -- thanks, Andrew.

**Comment by TimoGlastra** [comment]
ACA-Py now also depends on the `ursa_bbs_signatures` pip package which depends on the `bbs` crate (which comes from ursa)
