### ISSUE TITLE
DIDs for each connection - Aries Demo

### ISSUE THREAD

**Issue by GuilhermeMenezes** [hyperledger/aries-cloudagent-python#1211]
Hi, I hope I find you well.

I was told that on the Aries demo, a DID is established for each different connection, which means that for testing purposes I can't make Alice have the same DID on different connections, because a different DID is going to be given to her every time...  

Is it possible to avoid this situation, or is it possible to make the generated DID for the connection always the same if the agent connecting is Alice?

![image](https://user-images.githubusercontent.com/11176973/119867754-253ef200-bf16-11eb-92d3-459ff1e06052.png)

Maybe this image can help you understand the problem...On the left is a Faber agent(never mind the change on the name, that was just for testing purposes) and on the right is an Alice agent. On the right a DID is pointed out by an arrow, that's the DID Alice thinks Faber has, but if we look to the left, we can see the DID generated and established for Faber is not the same one.

Thanks in advance,
Cheers.

**Comment by sklump** [comment]
The DID on the left is Faber's public DID, which resides on the ledger. Issuers have public DIDs on the ledger so that holders and verifiers can verify their control of credential definitions, thereby establishing a chain of trust for credentials.

Per-connection (peer) DIDs are private, per-connection use - that's a core feature of self-sovereign identity. Peer DIDs avoid corroboration. If I have connections to a bank, an insurance company, and a government office, and the per-connection DIDs were the same, they could collaborate and build a dossier on me out of the scraps of proofs I presented to each. It's one of the very problems self-sovereign identity designs around.

**Comment by GuilhermeMenezes** [comment]
Thanks for the reply! It makes sense. Thanks!

**Comment by esune** [comment]
Closing as the issue appears to be resolved/answered.
