### ISSUE TITLE
ACA-Py 0.6.0: How do I implement Revocation registry?

### ISSUE THREAD

**Issue by Rounak210** [hyperledger/aries-cloudagent-python#1227]
I had integrated ACA-PY and could the steps I followed were:

1. Created Schema
2. Created Credential Definition ID with support revocation=true
3. Setup Von tail Server
4. Changed startup command added --auto-provision, --recreate-wallet, --tail-server-base-url {https://custom-url}.

Is this enough to setup revocation registry or am I missing something.?

**Comment by esune** [comment]
Assuming you have setup and started the tails server BEFORE you started aca-py with the tails server URL setting you should be good to go.

You will need to keep track of either the `credential-exchange-id` or `revocation-registry-id` and `revocation-id` for each issued credential (these attributes come back to you in the webhooks) in order to be able to revoke.

**Comment by Rounak210** [comment]
Thank you so much.
