### ISSUE TITLE
Feature:  Suggest alternative approach to providing connection information to indy ledger

### ISSUE THREAD

**Issue by SmithSamuelM** [hyperledger/aries-cloudagent-python#123]
The aries cloud agent is architected to extract the IP address of the nodes in the indy ledger from the genesis transactions for the ledger. If I am not mistaken this may be problematic in the future.  A given indy ledger may over time have a complete turnover in the nodes hosting the ledger and hence not share any IP addresses with the nodes that formed the genesis transactions. Given that the architecture choice of using the genesis transactions to bootstrap communications with the ledger is pervasive throughout the aca python design and shows up in numerous places in terms of command options etc. It seems that this might be a large latent problem and fixing it sooner rather than later would be prudent.  

Some suggestions. The current approach of using a web server / ledger browser as a mechanism for extracting information from a pool is one viable path. But as it currently stands even this browser requires (von-network) the ledger transactions in order to talk to the ledger.  

A public indy ledger should have a WELL KNOWN URL that provides the node IP addresses. This should be the architecture used for public ledger. In development environments or otherwise private ledgers a list of current node ip addresses should be trivially available and all agents either use that list or bootstrap by tasing to a ledger browser that provides that. But the IP connection should not be via the genesis transactions. 

Maybe I am missing something.

**Comment by swcurran** [comment]
I agree with the thought here, but I think it is an indy-node issue, not an aca-py issue.  Once a better mechanism is supported in indy-node for contacting the ledger from a genesis file, we can support it in aca-py.

Some additional points:

- the use of a URL for retrieving the genesis file works for other than von-network. For example, the Sovrin ledgers post their genesis files on github so that they can fetched via a URL.
- The "staging" (formerly known as test) Sovrin network recently had this issue that the handful of original IPs referenced in the genesis file were removed from the pool. I believe the solution they came to was to add all stewards to the genesis file. The file is available here: https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_sandbox_genesis

I don't see anything that should be done by ACA-Py specifically.  The genesis file is available in various forms depending on the use case - generally split between developer ledgers and more permanent ledgers and ACA-Py supports the different use cases.  We might want to add more docs around the use cases, but I don't think the functionality needs to change.

Will close this barring further comments/suggestions.

Thanks!

**Comment by SmithSamuelM** [comment]
I was missing something and that is the practice of adding all current nodes to the genesis file. So this is not a latent issue if indeed that practice continues.  I think then the one thing that ACA can do is support a local copy of the genesis file via a file path  not the contents of the file.

**Comment by swcurran** [comment]
Sounds good.  We have another issue for supporting adding the `--genesis_file <file>` option.

Closing this issue.

**Comment by SmithSamuelM** [comment]
I agree although genesis file is now a bad name if it includes more that the genesis nodes

**Comment by SmithSamuelM** [comment]
That’s up to the Indy guys to address
