### ISSUE TITLE
Performance issues after deleting connections and credential exchange records

### ISSUE THREAD

**Issue by lukwil** [hyperledger/aries-cloudagent-python#1232]
Hi,

Wer run aca-py in a cloud environment using the Postgres connector. Recently, we ran into performance issues leading to a duration of up to 5 seconds until a connection between two agents was fully established (including the whole process regarding "create invitation", "receive invitation", auto accept etc.).

After further investigation we found two issues with similar problems: #1192, #753 
But even after deleting all connections and credential exchange records the performance problems continued. 
The database showed a drop from around 15k to 11k entries (whilst using half the space afterwards).
I assured that everything (connections&credential exchange records) really got deleted by sending an API call and found out that a lot of wallet-only DIDs were stored which cannot be deleted (see also #1191).

Is there any possibility to clean those remaining 11k entries (or at least to get to know why there are still so many in the database)?

**Comment by swcurran** [comment]
@andrewwhitehead -- can you please look into this and respond.

Sorry for the slow response -- we've been "at" the Hyperledger Global Forum conference.

@ianco -- heads up.  We may need to get the tracing capability published so that people can use that to see where the performance issues are happening.

**Comment by ianco** [comment]
@swcurran  the tracing capabilities are out there in the latest release(s), however in this case I'm not sure they'd be much help.  It looks like the issue is due to (a) a large number of records in the database (in this case either connections or local did's), (b) the inability to delete these records, and/or (c) inefficient queries in aca-py/indy-sdk.  I know we had an issue with did queries in the past but I thought it was addressed.  There are some constraints because we're going through indy-sdk and storing everything in wallet non-secrets.

Possibly things will improve with the new shared components libraries.

**Comment by swcurran** [comment]
The tracing could confirm that the problem is with the queries to the DB.  We've assumed in the past where the issue was and discovered differently.    I definitely don't understand why such a low volume (11k to 15k) should cause an issue.

And agree that the sooner we're able to try this with the shared components the better.

**Comment by andrewwhitehead** [comment]
I'm looking at a few related changes which should make it into a PR soon. One part is a profile-level cache for things that should only be cached for the current request, like the active public DID. Most important here is adding a singleton record as a pointer to the current public DID, along with auto-population of that record for existing wallets. Third, I'll be looking at the wallet DID deletion options, although performance should be improved without having to delete leftover DIDs. Another possible fix would be to delete single-purpose related DIDs when the associated connection is removed.

**Comment by swcurran** [comment]
FYI -- some fixes were done ACA-Py to address this issue.  Are you able to run this scenario again to see if the issue has been addressed? PR was #1249 

@lukwil
