### ISSUE TITLE
Create and Consume the Same Schema

### ISSUE THREAD

**Issue by Marco77577** [hyperledger/aries-cloudagent-python#1322]
Hello there,

I am playing around with two agents, one of them issuer, the other one verifier (additionally, I am running a local VON network).

I created a controller for the issuer that will, on startup, create the required schemas and credential definitions to issue a credential. This works like a charm. However, when starting up the verifier, I am unsure on how I can retrieve the correct schema and credential definition id to request proofs from my wallets.

I could, of course, let the issuer start up and create both, then query them via some means (Admin API or VON browser), and then hard code them into the verifier. However, this does not seem the way to go for me (too many manual steps, error prone, and depending on the issuer being started before the verifier is coded).

Is there a way to query a schema via its name, version, and attributes? Or is there a way to query all schemas on the ledger that were created by a certain agent?

Or how does one usually retrieve the correct schema and credential ids, without hardcoding them?

Is there a protocol that allows two agents to agree on a schema and credential definition id?

**Comment by swcurran** [comment]
This is the core of the verifier's challenge -- what issuers do you trust and how do you decide?

In the "real world" and with paper credentials, we "hard code" the value -- we decide what credentials we want and ask for them: "Please provide your driver's license and one other piece of ID from a bank or utility company". For VCs, you are faced with the same issue.

For small use cases, with limited issuers, the right way to do it is to hard code the acceptable issuers/schema. For larger use cases, you probably still want to hard code the schema, but you might decide to accept (or not) an issuer after you receive a proof.  For example, as an employer, accept the presentation of a standardized "diploma" VC, and then check the issuer after verification, because you don't know all of the universities in the world.  Even then, you probably need to go to a registry of "valid" universities -- ones you trust to decide if you accept the presentation.

This is not really an ACA-Py issue, but one of VCs (and trust -- human and technical), as such I'll close this.  Alternatively, if you think there should/could be a protocol, suggest opening it at: https://github.com/hyperledger/aries-rfcs.
