### ISSUE TITLE
No OperationId's in the openapi.json

### ISSUE THREAD

**Issue by michaelwiles** [hyperledger/aries-cloudagent-python#1329]
So I'm generating client stubs with [openapi generator](https://github.com/OpenAPITools/openapi-generator) from the [openapi.json](https://github.com/hyperledger/aries-cloudagent-python/blob/main/open-api/openapi.json)...

But when doing that I discovered there are no operationId's in the file.

This means my methods that are generated are quite clumsily named.

Is this file generated? if so can the operationId's be included? If not, can I create a pull request to add these operationId's? It is a lot of work to add these operation id's though... But it only needs to be done once

**Comment by swcurran** [comment]
@jcourt562 -- please weigh in here on what is best to be done. I know you are looking at this same issue.

**Comment by jcourt562** [comment]
So I noticed operation Ids were never included in the output from ACA-py but never raised it because I thought it was intentional.  

For my part I went the way of writing a simple TS utility that allows the merging of OperationIds into the openapi.json file prior to doing the codegen step if people wanted to go that way, the Typescript SDK we release provides this utility.  

I think if you provide operationIds in the raw  OpenAPI ACA-py you will never make everyone happy so it could well be best to let people annotate it themselves.

In the sample REACT UI we publish I have just used the existing "clumsy" OpenAPI generated method names and isolated them in a `models` layer.  However this is more a case of I didn't want to manually name things whilst there is still a lot of flux in APIs (i.e. until ACA-py V1.0 is released).

**Comment by jcourt562** [comment]
So I should also comment on the `generated` question.  The openapi.json file is generated by the scripts/generate-open-api-spec utility.  However this is not automatically done on each build.  This was originally created so that differences in APIs could be seen before people committed changes or performed releases.  At that point there were issues around random ordering of parameters etc that were going undetected and a comparison of this output showed that up so it could be detected.

It seems to me you are wanting to move beyond this and like me trying to generate wrappers.  My suggestion would be that atm ACA-py as a product isn't focused on supporting that and its kind of a byproduct that it works.  If you want to do this I would suggest looking at scripts/generate-open-api-spec as an example and start from the raw ACA-py output it pulls from a running ACA-py.  The reason is that tbh there is a lot of nasty corners in each of the Swagger/OpenAPI generators that you will want to play around with before settling on one.  I am currently in the same process on deciding which generator to move to for 0.7.0.   If you want more details on how to generate take look at https://github.com/sudoplatform-labs/sudo-di-cloud-agent-js. or https://docs.sudoplatform.com/sudo-labs/decentralized-identity/cloud-agent-sdk

**Comment by swcurran** [comment]
@jcourt562 -- there is good content here, but I'm thinking it will get lost in this issue.  How about adding a "UsingOpenAPI.md" (or something like that) document is this, where you capture the ideas in here and experience you are having, to help others?

**Comment by jcourt562** [comment]
I can do that.  Let me get the 0.7.0 generation off my plate and I will open a PR.

**Comment by michaelwiles** [comment]
Thanks all...

@jcourt562 I am generating python bindings via a new openapi generator - when I saw the "weird" methods that were being generated is when I noticed the operationId's are not present.

Best case is that these operationId's can be added to the code so that they're embedded and are thus not generated and don't have to be manually added - though I suspect [aiohttp-apispec](https://aiohttp-apispec.readthedocs.io/en/latest/) would need to support this and a cursory scan of the the docs thereof did not find support for operationIds. I was hoping the route name would be rendered as operationId (I added some route names and it wasn't)... 

Okay - for now I'm just going to add these operationId's manually on my side (at least they can be python friendly then) before generating my client. It's not a big deal as I don't expect functionality to change "en masse" and when new methods are added I can just compare with old and add the new operation Ids.

That UsingOpenAPI.md would be wonderful. Glad I found out how it's generated as I want to generate one that includes the multitenancy endpoints.

Happy for this issue to be closed.

**Comment by jcourt562** [comment]
@michaelwiles I would still suggest you automate this to some extent.  Take a look at the merge Typescript utility at https://github.com/sudoplatform-labs/sudo-di-cloud-agent-js/blob/main/src/operationids-merge.ts and https://github.com/sudoplatform-labs/sudo-di-cloud-agent-js/blob/main/src/operationids-merge.ts

Hopefully you would be able to use those as is if you have node installed or create a python equivalent since manually going through an openapi.json is painful and hard to track if it changes.

**Comment by jcourt562** [comment]
@michaelwiles there is now a "UsingOpenAPI.md" in the repo.  If this is satisfactory could you close this issue as I don't have permissions to do so but the issue creator would have.
