### ISSUE TITLE
Inconsistency in proof presentation in v 0.7.1

### ISSUE THREAD

**Issue by deoalade** [hyperledger/aries-cloudagent-python#1499]
HI all,

I’ve recently been working with Hyperledger Aries (versions 0.6.0 & 0.7.1) & have generally found it to be a really amazing framework.

However I notice there seems to be some inconsistencies resulting in errors when executing some of the API calls for the Acapy agents in version 0.7.1.

For instance I am sometimes successfully able to run a full sequence of schema/credential definition, credential request/issuance & credential verification on a new instance with my Issuer, holder & verifier nodes.

However, when attempting to run the same sequence again for a new proof presentation I get the following error at the point of the send presentation requestl:

**Error when constructing revocation state: Error: Invalid structure. Caused by: UrsaCryptoError: Invalid len of bytes representation for PoingG2. CommonInvalidStructure.**

These are the steps I have taken:

Step1: Send a presentation request (p.s. I attempted following the format suggested in the openapi but it appears to require the object name proof request as opposed to presentation request):
![image](https://user-images.githubusercontent.com/18369850/141962250-b57cafbe-51ee-4b25-b4de-a5f0e544dd4d.png)

Step 2: Send the presentation using the following request:
![image](https://user-images.githubusercontent.com/18369850/142230251-17dca319-63f7-4ea8-a9c2-3acf7c8e25d6.png).
(Please ignore the discrepancy in timestamps between both screenshots. The images were captured @ different times)

Could you please help me understand why this inconsistency occurs & how to potentially fix it?

**Comment by ianco** [comment]
@deoalade  Can you include the contents of the aca-py log for this error?  Especially if there is a stack trace in the log ...

**Comment by swcurran** [comment]
Closing this due to lack of access to the logs.  However, this is very similar to #1598 , where a second run through the presentation process produces an Ursa error. That makes little sense, but significant that it multiple people are seeing this.

I assume that you are generating and sending a new presentation based off the second presentation request -- correct?  E.g. you aren't literally sending the same presentation on the second run.  That would generate an error -- as expected. The presentation request sent will have a unique nonce per request, and so using the same presentation twice will generate an error.
