### ISSUE TITLE
Delete wallet only DIDs

### ISSUE THREAD

**Issue by lukwil** [hyperledger/aries-cloudagent-python#1520]
Hi,

We did some more extensive performance testing with version 0.7.1 since our last issue here (#1232). For reference see the graph below.

To be exact, we did full end to end tests with 20 requests/minute, with emulated end user wallets as well as a mediator service and aca-py cloudagents for the issuing side. At some point in time (around 1200 credentials issued), we were somehow reaching a performance bottleneck, leading to an increasing time for the whole credential issuance process. Every one of those processes consists of the establishment of a connection beforehand, thus resulting in many wallet only DIDs. Since there’s currently no way (at least not one I’m aware of) to delete them in the aca-py API or the Indy SDK the database is growing to multiple hundred MB over time (nonetheless we should not expect a dramatic degradation with this size anyway). The improvements made before for the current version did unfortunately not have an impact on that. We have also always deleted the connection and the credential definition record after a completed process run. We also tried restarting the service around 11:15, which did not have an impact on performance. After purging the database around 12:00, performance went back to normal. Do you have any suggestions how we can solve this issue in the near future? We would also be willing to contribute a draft ourself, if we had a bit of guidance on where to start best.
![EXECUTION --- POST issue-credentialrecords-scatter](https://user-images.githubusercontent.com/30203234/143428563-33e46d2b-8000-4bf0-be9e-69898d5cc55d.png)

**Comment by swcurran** [comment]
This is awesome -- thanks for contributing this.

One thing that I would like to see tried if possible, is running the entire scenario with the "shared components" (e.g. indy-vdr, indy-shared-rs and aries-askar) instead of the indy-sdk.  While that won't address the "delete" issue, it would be extremely interesting to us to have an "apples-to-apples" comparison of an indy-sdk and shared components performance test.  It **should** be as simple as changing the "wallet-type" parameter to `--wallet-type askar` (@ianco please jump in if there is more to do).

Beyond that, our team will get together to talk about how we can help with what you are doing.

Would it be possible for us to access your test setup?  That would help us in evaluating how we can collaborate  Any possibility that this could be made into an open source repo -- perhaps even within the Hyperledger Aries project? 

@jljordan42 -- FYI for you on this work.

**Comment by ianco** [comment]
> One thing that I would like to see tried if possible, is running the entire scenario with the "shared components" (e.g. indy-vdr, indy-shared-rs and aries-askar) instead of the indy-sdk. While that won't address the "delete" issue, it would be extremely interesting to us to have an "apples-to-apples" comparison of an indy-sdk and shared components performance test. It **should** be as simple as changing the "wallet-type" parameter to `--wallet-type askar` (@ianco please jump in if there is more to do).

Yes you just need to specify `--wallet-type askar` and it will run with the shared components.

(Note that the integration tests and AATH tests can also be run with the askar components, by specifying this parameter)

**Comment by lukwil** [comment]
First of all thanks for your fast answers! I tried Askar before (but still in 0.7.0rc0) and did not see any significant improvements. But we will give that a try in our more "close to production" test environment. Concerning your question @swcurran about access to our setup - I will clarify whether that is possible 👍🏻

**Comment by andrewwhitehead** [comment]
It may be possible to use the `--public-invites` flag to establish these connections without creating a new peer DID for each instance. This should avoid the overhead of creating the thousands of DIDs and filtering them on each request. There is a security trade-off due to the nature of the current DIDComm envelope formats – future exposure of the private key for the agent's public DID would allow for any past messages prepared by or for that agent to be decrypted. With the default configuration messages for each connection would be protected by different keys, but exposure of the decrypted wallet contents would still allow for any past communication to be decrypted. (In either case, requiring TLS would still provide forward secrecy for messages in transit.)

**Comment by swcurran** [comment]
It would be good to use the https://github.com/lissi-id/aries-cloudagent-loadgenerator to try out this scenario.  Did this work evolve into the Generator?

I'm going to close this issue as a lot has been done on performance under load since this was done. Askar is significantly better than the Indy SDK implementation.
