### ISSUE TITLE
Unable to use HTTPS for ACA-Py Agent

### ISSUE THREAD

**Issue by naman20sharma** [hyperledger/aries-cloudagent-python#1552]
### Unable to use HTTPS for the agent 
Hi, 
I've been trying to run an agent with below configuration, but I want it to run on HTTPS instead http. The agent's Wallet-DID Endpoint is also listed as `https://127.0. 0.1:8060` which I confirmed used admin swagger apis.
````
PORTS="8060:8060 8061:8061" ./run_docker start --endpoint https://127.0. 0.1:8060 \
--label alice \
--auto-ping-connection \
--auto-respond-messages \
--auto-accept-invites \
--auto-accept-requests \
--auto-respond-credential-offer \
--auto-store-credential \
--inbound-transport http 0.0.0.0 8060 \
--outbound-transport https \
--admin 0.0.0.0 8061 \
--admin-insecure-mode \
--auto-provision \
--wallet-type indy \
--wallet-name org12345 \
--wallet-key org12345 \
--auto-provision \
--genesis-url http://127.0. 0.1:9000/genesis \
--seed 08c67d9d28a8f59c91bc365f61618720`
````

**Error while connecting with this agent**
I've received the `ERR_SSL_PROTOCOL_ERROR` on the Connection invitation url.

Can I anyone please help ?  I want an ssl certified agent running on HTTPS . and in agents command can we provide a certified DNS instead of an ip ? @swcurran @andrewwhitehead

**Comment by frostyfrog** [comment]
I believe that the IP is required for binding purposes. As far as connecting and interacting with the ACA-Py agent, you should be able to use a FQDN instead of an IP address by specifying an endpoint. For example: `--endpoint https://mydomain.example.com/`

From my experience, the cloud agent seems to be typically run through a docker container and uses an nginx reverse proxy (also in a container) to provide https support. and keep the raw ports from being exposed to the web.

**Comment by naman20sharma** [comment]
@frostyfrog cloud agent is running through a docker container only. My concern is exposing the port `8060` to the web, as in current configuration I have to do that. How to use an nginx reverse proxy here to avoid exposing that port? In my case, I have to connect with a mobile agent as well with this web agent.

**Comment by frostyfrog** [comment]
I'm not certain how to setup an nginx reverse proxy myself since most of my reverse proxy experience lies with lighttpd outside of a docker container. I do know that the proxy is also able to run within a docker container, just like the aries-cloudagent, and I'm almost certain that there's plenty of guides online to help you set one up.

**Comment by swcurran** [comment]
Closing this -- outside the scope of ACA-Py.  We'd welcome a PR with documentation about this if it could be helpful to others.
