### ISSUE TITLE
Can I re-use a Peer DID in another connection?

### ISSUE THREAD

**Issue by estrehle** [hyperledger/aries-cloudagent-python#1582]
Upon receiving an invitation, the ACA-Py agent generates a new Peer DID as `my_did`. Is it instead possible to re-use an existing Peer DID (not a public DID) from my wallet?

I have a business case where I want two of my contacts to know that they are both connected to the same agent (i.e., me).

**Comment by swcurran** [comment]
@andrewwhitehead @shaangill025 -- thoughts on this?

As implemented today, I don't think that is possible, but there is no Aries protocols reason for this not to be supported.

I know a common discussion in the community has been an enterprise agent using the same public DID as the DID for all connections (e.g. don't use a peer DID at all). I think (but am not sure) if that is supported today in ACA-Py. 

The question in what you are requesting is whether you want to use the same DID (peer or public) for ALL connections (a global setting) or if you want to selectively use the same DID for specific connections (a per connection setting).  And if the latter, how do you see managing that?

**Comment by shaangill025** [comment]
> Upon receiving an invitation, the ACA-Py agent generates a new Peer DID as `my_did`. Is it instead possible to re-use an existing Peer DID (not a public DID) from my wallet?
> 
> I have a business case where I want two of my contacts to know that they are both connected to the same agent (i.e., me).

I think the following approach will meet this requirement:
- updating `recieve_invitation` (`OOBManager`, `ConnectionManager` and `DIDXManager`) to accept an `optional peer_did` parameter and pass that to `create_request` (`ConnectionManager` and `DIDXManager`) where if this specified we use to `get_local_did` and set it as connection.my_did.
- This is a per-connection approach and is based upon the assumption that we want to continue using peer DID

**Comment by swcurran** [comment]
Would that cause any issues in knowing from whom a message came?  That is, what do we do to find the connection from which a message has been received?  If we use the peer DID, or the public key of the peer DID, would we know from which connection the message was received?

**Comment by shaangill025** [comment]
I am testing it with draft PR #1585, haven't found any issue yet. @andrewwhitehead I will appreciate your feedback.

**Comment by estrehle** [comment]
@swcurran @shaangill025 Thanks for taking this on! I'll take a look at the PR and test it for my use case. I want to selectively use the same peer DID for specific connections, and I would manage the logic behind that in a custom Aries controller.

My use case is about managing access to documents hosted by a third party:
- Alice owns a document (e.g., her high school diploma)
- This document is hosted by Charlie (because Alice only has a mobile phone and Charlie operates a professional file hosting service)
- Alice wants to inform Charlie that her friend Bob is allowed to download the document from Charlie

Most of this can be implemented with current ACA-Py functionality. But I found it very difficult to model the third step: How can Alice tell Charlie about Bob when Bob has no public identity? My targeted solution, which lead to this issue, is to have Bob re-use his Peer DID from the Bob-Alice connection in the Bob-Charlie connection. In that way, Alice and Charlie are connected to Bob with the same identity, so Alice can tell Charlie: "Peer DID [Bob-Alice] has permission to download my document".

**Comment by andrewwhitehead** [comment]
@estrehle  I don't think that would provide the desired security at the moment. Theoretically a peer DID can be verified (ie. ensuring that the other party possesses the key used to derive the peer DID), but at the moment this is not checked. Since the DID document itself is sent during the connection process, any party could choose to use the Bob-Alice peer DID with their own key.

**Comment by estrehle** [comment]
Thanks for pointing this out! I was not aware of this ... apparently I missed that in the protocol description.

**Comment by andrewwhitehead** [comment]
It does encrypt all messages, and so the sender must possess the key that is listed in the DID Document. It's just the deterministic relationship between the public key and the `did:peer` identifier that is not enforced in the current version.

**Comment by swcurran** [comment]
My feeling is that we should not add this feature in and the WIP PR should be dropped.  Let's discuss this in an ACA-Pug call.

**Comment by estrehle** [comment]
We need this for a research project on DIDComm-based exchange of medical data. I would be happy to provide more details and talk about implementation options on a call or via email (elias@circulartree.com).

**Comment by swcurran** [comment]
It's been a while for this. We've not moved this ahead.  @estrehle -- wondered if you came up with another way to do this, or just moved on?

We came up with the idea of an "introduction" protocol some time ago. I wondered if that would meet this use case.  We want a way for Alice and Charlie to both reference the same third party -- Bob.  With the introduction protocol (at least as I think of it...) Alice  is connected to Charlie and to Bob, and wants to connect the two of them. Alice sends a "request for an invitation" to Charlie, who creates and invitation and sends it to Alice. Alice sends that on to Bob.  Bob process the invitation and connects with Charlie. Since Alice, Bob and Charlie all participated in the same invitation protocol (with a single protocol ID), all have a common identifier.  As well, the invitation ID would also be visible across all three.

I think that would be a more sustainable approach to this use case than sharing peer DIDs.

**Comment by estrehle** [comment]
We came up with another way by using a token. Alice generates a token and sends it to Bob and Charlie. Bob connects with Charlie and sends the token to Charlie. In this way, both Alice and Charlie can reference Bob.

The token approach works for us but feels hacky. Your introduction protocol would work as well, and I agree with you @swcurran that it seems like a sustainable approach.

**Comment by swcurran** [comment]
I'm going to close this issue as not something we want to do.  I will likely add a "get introduction protocol working", but as I mentioned, I think it needs some work to the Aries RFC before it can be really useful.
