### ISSUE TITLE
Define predicate in Proof Request that checks expiration date and returns true/false

### ISSUE THREAD

**Issue by srbms23** [hyperledger/aries-cloudagent-python#1613]
I have a credential in my wallet that contains property "licenseCategoryB_DateOfExpiry" and it has value for example:
`{
        "name": "licenseCategoryB_DateOfExpiry",
        "value": "2028-02-25"
    }` 
Once I send proof request that requests `licenseCategoryB_DateOfExpiry` I would like to just return `true/false` depending on the current date, not whole value (2028-02-25). Is there a way to do that with Predicates?
I saw couple of examples online with age but in that case there is only single integer and <,>,>=... Is there something like that for date type? 

Thanks! :)

**Comment by swcurran** [comment]
The "easy" way to do it today in anoncreds is to make your date data a number (not a string), so that in your case, the value would be the integer `20280225`.  If you do that, and in the proof request, the verifer asks that `licenseCategoryB_DateOfExpiry > 20220128`, the predicate will return true in zero knowledge.  This convention is described here: https://github.com/hyperledger/aries-rfcs/tree/main/concepts/0441-present-proof-best-practices#dates-and-predicates  The nice thing about this approach is that at least the integer looks to a person like a date  -- much better, for example, than a Unix epoch representation.

Why this way?  In AnonCreds, the signed data is an integer encoded based on the "raw" data being asserted. Thus, there must be agreement between the issuer and verifier about how the "data to integer" encoding is done for signing by the issuer. Currently, that encoding algorithm is very simple -- integers are unchanged, everything else is a string, which is hashed to an integer.  Thus, the only data that can be used as a predicate is an integer. The convention above is helpful given those limitations.

We are starting on the path of standardizing AnonCreds and one possibility in the future is adding in more rules in to the encoding, so that a date string might be encoded as a sortable integer, and that a presentation predicate proof would handle the expression in the same way.  But that's not there yet.

**Comment by ianco** [comment]
> The "easy" way to do it today in anoncreds is to make your date data a number (not a string), so that in your case, the value would be the integer `20280225`. If you do that, and in the proof request, the verifer asks that `licenseCategoryB_DateOfExpiry > 20220128`, the predicate will return true in zero knowledge. This convention is described here: https://github.com/hyperledger/aries-rfcs/tree/main/concepts/0441-present-proof-best-practices#dates-and-predicates The nice thing about this approach is that at least the integer looks to a person like a date -- much better, for example, than a Unix epoch representation.

Note `the attribute name SHOULD have the suffix _dateint`

The alice/faber demo includes this:  https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/runners/faber.py#L109
