### ISSUE TITLE
--multitenant-admin security questions

### ISSUE THREAD

**Issue by matgnt** [hyperledger/aries-cloudagent-python#1632]
I'm currently testing multitenancy a bit and have a question whether the following is intended behavior:
Reading from here:
https://github.com/hyperledger/aries-cloudagent-python/blob/main/Multitenancy.md#authentication

> When multi-tenancy is not enabled you can authenticate with the agent using the x-api-key header. As there is only a single wallet, this provides sufficient authentication and authorization.

> For sub wallets, an additional authentication method is introduced using JSON Web Tokens (JWTs). A token parameter is returned after creating a wallet or calling the get token endpoint. This token must be provided for every admin API call you want to perform for the wallet using the Bearer authorization scheme.

So as I understand, (also tried, but without api-key enabled)
For sub-wallet calls I need both, api-key + jwt
For base-wallet (multitenant admin api) I need the api-key

But with the api-key I have access to the `/multitenancy` endpoint and I get a list of all sub-wallets (here, without the jwt token), but with an additional call to `/multitenancy/wallet/{wallet_id}/token` I receive the same token that I received when creating the sub-wallet.

This looks to me that without any additional API layer in between, the system that is allowed to create a sub-wallet could get access to any other sub-wallet that is hosted here.

Am I missing something in my tests / thoughts?

Thanks for your opinions on this,
Matthias

**Comment by ianco** [comment]
That's correct, you should not give the tenants direct access to aca-py, you should have a service layer that your tenants access which mediates the calls to aca-py.

You can see an example of this kind of service layer here:  https://github.com/bcgov/traction  (note this is work in progress)

There are some custom services implemented, however it also includes a proxy api to aca-py which handles the security:  https://github.com/bcgov/traction/tree/develop/services/traction/acapy_wrapper

**Comment by matgnt** [comment]
Looking into the traction acapy_wrapper code a bit and asking myself if it wouldn't make sense that 
`/multitenancy/wallet/{wallet_id}/token`
would only return the token when the wallet_key is provided? That is at least what I understood how it is done there in the acapy_wrapper.
Or why does the endpoint have this field in the payload? Only for the 'unmanaged' mode?
I would argue that this should be the default also for the 'managed' mode. Currently the wallet_key is not required to receive the token.
Probably the question is: Should the acapy admin api be able to access a wallet without the key that has been used to create it?
Possible answers: Yes, because it manages / stores the keys anyway OR no, only when the creator of the wallet provides the key.
I suppose, the decision was the latter one :-)

**Comment by ianco** [comment]
> Thanks @ianco for the clarification. Do you think it makes sense to add some further notes regarding this to the "Authentication" section of the documentation? It might not be clear to everyone - just to avoid security issues here.

Yes we should update the documentation, this is a common observation lol

**Comment by ianco** [comment]
Maybe a question for @TimoGlastra  ...  there is an attribute on the wallet record called "requires_external_key", which returns "False" for managed wallets.  This is checked in the `/multitenancy/wallet/{wallet_id}/token` endpoint, so for managed wallets (which is all sub-wallets for now) a wallet_key is not required.

However for this particular endpoint, it makes sense (to me) to always require a wallet key.  The token generated by this endpoint is only used for the admin api, and the sub-wallet user should know their wallet key.

(When I've used this endpoint I've always supplied a wallet_key and it always seems to work ...)

**Comment by matgnt** [comment]
Can we mark this as "security" relevant?
In case the controller uses the mentioned API trusting that the secret is checked, it would reveal access to any sub-wallet, right?
Assuming the attacker knows the wallet_id?

**Comment by chriamue** [comment]
Smells like OWASP number 1 https://owasp.org/Top10/A01_2021-Broken_Access_Control/
* Violation of the principle of least privilege or deny by default, where access should only be granted for particular capabilities, roles, or users, but is available to anyone.

**Comment by TimoGlastra** [comment]
Hi @matgnt, sorry for the late reply.

I agree the current approach is not perfect, but the way it currently works is intended behaviour. As mentioned by @ianco the API should never be exposed directly and always proxied through another API that handles the authentication.

I tried to quickly map it out in a diagram to highlight how I would build on top of this. If you think this approach is insecure please let me know. In this diagram the ACA-Py admin API is not exposed to the public, and the admin api key is only injected by an internal service.

![image](https://user-images.githubusercontent.com/23165168/155965981-5df21334-702e-4caf-9666-78562c96128d.png)


We've discussed not requiring the admin api key for tenants (so the admin api key is only used for the base wallet) during the ACA-Py WG call and it was discussed that as ACA-Py shouldn't be exposed as a public API we don't have to do this.

Re the comment from @ianco:
> and the sub-wallet user should know their wallet key.

I'm not sure this is always the case. We're using multi-tenancy for an agency infrastructure where the wallet key is generated. The user doesn't care about their wallet key here and is completely managed by ACA-Py.

Making the wallet key required for the token endpoint would also mean that if the wallet key is lost, access to the wallet is lost (without retrieving it manually from storage, but this can't be done through the api), which is not what I would expect in a managed workflow (think of providers like trinsic, they 'manage' the wallet key for you). 

I see the admin api really to provide _admin_ access to the API and give access to tenants.

If we make the wallet key required, it would make more sense to make the API available to the tenants (instead of the admin) so they can generate a token themselves, but this would mean the wallet_key has to be stored in another place than ACA-Py encrypted storage.

**Comment by matgnt** [comment]
Yes, absolutely understand the arguments that this is intended behavior.
I only see the danger, that developers of the controller have wrong assumptions about this endpoint - which is in consequence very critical regarding the overall security.

As @ianco  said:
> Yes the wallet_key should be provided, I thought it was :-S I'll look into this ... thanks

> When I've used this endpoint I've always supplied a wallet_key and it always seems to work ...

and for me it was similar.

@TimoGlastra  Do you have and idea how we could make this more visible / highlight it to the users of the admin api?
Removing the payload could be 1 option - problem: Would not work for the unmanaged case

**Comment by TimoGlastra** [comment]
I agree with you. It is causing a lot of confusion. Maybe we can remove the parameter and create a new endpoint once unmanaged mode is supported.

This way we can clearly mark that only the unmanaged mode needs an API key

As I wrote it, it has always been obvious to me. But there's really no way to know without looking at the code.

The other option is extending the docs (which would be a good thing to do either way)

**Comment by matgnt** [comment]
+1 for separate token endpoints: 1 for managed (without key) and 1 for unmanaged (with the key parameter)!
I think this makes it very clear, right from looking at the API.

**Comment by ianco** [comment]
The reason we need a "managed" mode (and therefore for aca-py to know the wallet_key) is so we can process inbound messages as we receive them.  (Note that once we have persistent queues we will have the ability to store messages and we can think about implementing an "un-managed" mode.)

On the admin api side, I think there's an issue if we provide api access to the wallet without requiring the wallet_key - basically a nefarious admin can get access to the wallet and retrieve credentials, issue credentials, etc posing as the wallet owner.  (I don't think there is the same security issue allowing aca-py to autonomously process inbound messages.)

Hence I think we should require the user to provide the wallet_key in order to obtain the wallet token for the tenant sub-wallet.  (And yes I agree @TimoGlastra  if we lose the key we lose access to the wallet.)

Separate endpoints is probably a good solution.

Maybe this would be a good topic for the next aca-pug call @swcurran  ...

**Comment by TimoGlastra** [comment]
Yeah would be good to have a discussion about this during the ACA-Pug call!

**Comment by matgnt** [comment]
Any updates on this? Did you discuss in the call you mentioned? @TimoGlastra  @ianco

**Comment by ianco** [comment]
We didn't discuss in the aca-pug @swcurran 

My recommendation would be separate endpoints, and a startup parameter to configure whether to allow "un-secured" calls to the `/token` endpoint (vs requiring the wallet_key).

Once we have un-managed sub-wallets this shouldn't be an issue, as implementers who want to enforce use of the `wallet_key` can just require all sub-wallets to be un-managed.

**Comment by ianco** [comment]
Closing, replaced by issue #1681
