### ISSUE TITLE
did:key connection - what is the actual did:key of the other end

### ISSUE THREAD

**Issue by matgnt** [hyperledger/aries-cloudagent-python#1635]
I'm trying to use W3C credentials and for this, I follow the instruction to issue a credential from here:
https://github.com/hyperledger/aries-cloudagent-python/blob/main/JsonLdCredentials.md#issuing-credentials

The documentation says:
>with the example body below and the connection_id and issuer keys replaced. The value of issuer should be the did that you created in the [Did Method](https://github.com/hyperledger/aries-cloudagent-python/blob/main/JsonLdCredentials.md#did-method) paragraph above.

Do I need to establish a connection first? I guess yes. I did that to have a `connection_id` that can be used in the issuing process.
Now I'm wondering a bit, how would I know the `did:key` from the other end of the connection?
The `their_did` field of the connection contains a peer did that has been created during the connection built-up.

How can I make sure, the participant on the other side of the connection is really the one behind a certain `did:key` - I want to know this before I issue a credential.

Does this make sense or am I missing something here?

Thanks in advance,
Matthias

**Comment by swcurran** [comment]
The DIDs used for connections and the DIDs for the issuing do not have anything to do with each. The issuer DID needs to be a published key that anyone -- any verifier -- can get to.  DIDs used in connections are generally private between the two participants in the exchange. An issuer may decide to use the public DID for both connecting to all holders and for issuing credentials, but that is generally considered a bad practice in the community.

Unlike with AnonCreds (aka Indy VCs) where the DID and related issuing objects go on a ledger, there is not a standard place to publish the DID of the Issuer. For LD Signatures, you can publish a DID on an Indy ledger and use that for the Ed25519 key. That is not yet possible for a BBS+ credential -- that is an issue left up to the issuer to decide and implement.

It looks like you are also asking in the above how does the holder get it's DID to the Issuer (with proof they own/control the DID) to be embedded into the issued credential. Again, that is up to the issuer to decide, and, unlike AnonCreds, there is not a well known way of doing that. In AnonCreds, the "master link secret" is the equivalent functionality of the Holder giving the issuer a DID to put into the VC. I don't think I would not to use "Their DID" from the connection as the "Subject DID" in the VC, since the DID for the connection is likely intended to be private between the issuer and the holder.

**Comment by matgnt** [comment]
Thanks @swcurran for your help! I further looked into the topic and came up with the following way of finding out who is on the other side of the connection (with did:key in mind...). Would appreciate your comments on the following...

![did_key_connection](https://user-images.githubusercontent.com/198707/155740657-f0d65468-9309-4080-95db-08d51e786526.png)
The VC could look like the following:
```
{
  "connection_id": "ec110c38-fe4e-4080-9bc1-f2b3964b314e",
  "filter": {
    "ld_proof": {
      "credential": {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          {
            "st": "http://supplytree.org/ns#",
            "BearerCredential": "st:BearerCredential",
            "nonce": "st:Nonce"
          }
        ],
        "type": [
          "VerifiableCredential",
          "BearerCredential"
        ],
        "issuer": "did:key:z6MkuAcDrhk3XoCVCQLaySQvscXPXsT5sAj2MmRwfxLVcQnv",
        "issuanceDate": "2022-02-22T08:00:00Z",
        "nonce": "XXX",
        "credentialSubject": {}
      },
      "options": {
        "proofType": "Ed25519Signature2018"
      }
    }
  }
}
```
Afterwards, I can issue VCs to the other end of the connection - knowing their DID.
Any comments whether this makes sense?

**Comment by matgnt** [comment]
Closing the issue. did:key is not the focus.
