### ISSUE TITLE
wallet_create_did doesn't accept seed as an argument to create did

### ISSUE THREAD

**Issue by DaevMithran** [hyperledger/aries-cloudagent-python#1640]
The wallet/create/did api should accept a seed which can be used to create the DID. 

pull request: https://github.com/hyperledger/aries-cloudagent-python/pull/1641

**Comment by swcurran** [comment]
We think this is a security risk. If you do this you are essentially putting your private key into an HTTP request to another service that anyone with visibility into the api traffic can see.

I don't think we will accept this PR -- to be confirmed by the core developer maintainers.  Sorry about that.

**Comment by DaevMithran** [comment]
@swcurran we can accept an encrypted seed, which is encrypted using wallet_key. so that it's secure. 

DID is wallet dependent without this. E.g. What if i a user wants to export this DID from an Indy wallet to an Askar wallet etc.

**Comment by swcurran** [comment]
I'm not sure on this one -- hopefully others will weigh in -- @ianco @WadeBarnes.

For public DIDs -- those posted to a ledger, we tend to put the seed in a secrets location -- e.g. 1Password or something like that. Not at all scalable, but adequate for some use cases.

The export use case is interesting -- not one I would expect.  We backup secure storage (e.g. askar) and assume that on recovery, we need the whole database, not just specific DIDs. For an issuer for example, there is no such thing as a seed for a CredDef, so those would lost.  Could you expand on why single DID sharing across secure storage instances is needed?

Thanks

**Comment by ianco** [comment]
Using a seed gives you a way to reproduce a did/verkey (as opposed to the existing `/wallet/create/did` which gives you essentially a random did every time), however I don't think there's a benefit to this in the multitenant use case.

Either you're recreating a wallet and want the same public did - as Stephen mentions this isn't useful because you lose all the related material in the wallet, such as credential definitions.

Or you are trying to create multiple wallets with the same public did - this is an anti-pattern since the wallets will try to publish conflicting endpoints and a did can only publish a single endpoint.

If you want to be able to convert between indy/askar wallets this will require full export/import support.

If there's a specific use case we can see how we can support it, but in general I don't think we *need* to support seeds in this create did method.

**Comment by WadeBarnes** [comment]
I agree with @ianco.  When you export from a wallet, it's typically and all or nothing process.  It is atypical to export or reuse individual DIDs.

**Comment by DaevMithran** [comment]
Agree I didn't think of losing credential definition keys.

**Comment by jpbu** [comment]
Hi @swcurran , @ianco , @WadeBarnes , since we have similar challenges, I would like to challenge a few of the points mentioned above - let me know if you prefer to have the discussion in a new issue since this one is closed.

* Security concerns: I believe it can be assumed that the REST API of ACA-Py is always used internally and thoroughly protected, since it effectively gives the control over the wallet. So I don't see that much of a difference to also expose the seed or private key for import or export purposes. Aries Framework Go provides endpoints to import keys in JWK format (see https://github.com/hyperledger/aries-framework-go/blob/v0.1.7/pkg/controller/rest/kms/operation.go#L83 and https://github.com/hyperledger/aries-framework-go/blob/main/docs/vc_wallet.md#add). If there are concerns that developers use this in a wrong way by mistake, the implementation could be put behind a feature toggle or other configuration flag to enable it.
* Specific use case: We have requirements to work with the same key pairs / wallets in our own application and for DID, Indy and Aries related operations. For the latter, we would like to utilise the ACA-Py multi-tenant feature, but still have the possibility to work with the private key directly in our own application logic.
* Export / reuse of individual DIDs: we believe this is relevant and needed in the multi-tenant case, e.g. if a single tenant later wants to migrate to its own agent keeping the DID and credentials. Is there any way to achieve this currently?

**Comment by DaevMithran** [comment]
> * Export / reuse of individual DIDs: we believe this is relevant and needed in the multi-tenant case, e.g. if a single tenant later wants to migrate to its own agent keeping the DID and credentials. Is there any way to achieve this currently?

@jpbu  for this specific use case. I think this will be possible in unmanaged wallets as unmanaged wallets have a wallet key which will be needed to provision the wallet. 

We store multitenant wallets in separate databases. We can just export that particular wallet from the postgres db.

In case of managed wallets I was proposing this https://github.com/hyperledger/aries-cloudagent-python/issues/1639

P.s: I believe unmanaged wallet development is in progress.
