### ISSUE TITLE
revocation notification webhooks should use `revocation_notification` instead of `revocation-notification` as the topic

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1713]
Not making a PR right away as it will be a breaking change, but I think revocation notification is the only topic that uses a dash instead of an underscore for the topic.

**Comment by swcurran** [comment]
Some thoughts:

- Do we really need to make this change?  It's uncomfortable, but is it actually crucial to change?
- If it is crucial to change, we should do it sooner than later I think.  revocation-notification was new in 0.7.3, so there are few implementations done -- especially since there is little in-the-wild support in Mobile apps. If we have to, let's do it ASAP.
- How do we prevent these in the future?  I know we do a lot of linting in the CI pipeline -- should/could this have been caught?

Thanks!

**Comment by TimoGlastra** [comment]
No we probably don't need this change, it will only break current implementations and doesn't improve the framework perse. 

I just wanted to raise this issue to bring it to developers attention as consistency can greatly reduce the complexity of working with a framework. I ran into issues because I assumed (never good to assume :) the topic would be `revocation_notification`

I think this is really hard to catch using linting / CI. What may be possible is to add a test that finds all subclasses of the base record and checks if the topic is formatted according to standards (no spaces, use `_` instead of `-`) using e.g something like this: https://stackoverflow.com/a/17246726. But this only helps with preventing it for this specific issue, so not sure if that's what we're looking for

**Comment by swcurran** [comment]
Per the last note, I'm going to close this issue.
