### ISSUE TITLE
ZPK Value must be one of <, <=, >=, >

### ISSUE THREAD

**Issue by edbkei** [hyperledger/aries-cloudagent-python#1732]
It may be my misundestand, but I´ve tried logical expression == for a simple ZPK in Faber.py, and the result was:

Exception: Error: {"presentation_request": {"indy": {"requested_predicates": {"0_eval_GE_uuid": {"value": {"p_type": ["Value == must be one of <, <=, >=, >"]}}}}}}

Not satisfied with this result, I´ve done another try:

          req_preds = [
                    # test zero-knowledge proofs
                    {
                        "name": "eval",
                        "p_type": "<=",
                        "p_value": eval_int,
                        "restrictions": [{"schema_name": "energy schema"}],
                    },
                    {
                        "name": "eval",
                        "p_type": ">=",
                        "p_value": eval_int,
                        "restrictions": [{"schema_name": "energy schema"}],
                    }

                ]

Then, I set 123 to variable eval in a credential that I created, for ZPK.

so, I´ve made several combinations:
case eval_int is
   when 123, result is True,   # situation 1
   when 122, result is False,  # situation 2
   when 124, result is True    # situation 3
end case

Conclusion:  Situation 1 OK, Situation 2 OK, but Situation 3 NOT OK. Despite, req_preds looks being a list of conditions be acceptable, only the first one is valid.

Is it possible equal condition in any manner? And is a list of conditions possible?

**Comment by swcurran** [comment]
Interesting result -- not good.  Agree that situation 3 should have been False.  It might be worth trying a few more examples, including where there are multiple different claims, some of which meet the condition, others don't. It should not matter that the same claim is used in multiple predicates.

An alternative is to put the claim into the requested attributes array, with a restriction on the claim equaling the value. In that case, the credential would not be usable for the presentation. Since the verifier will know the value from an "equal" condition of a successful proof, the use of a predicate is not hiding any information.  AFAIK, that was the rationale for not including the "=" in the list of conditions.

**Comment by ianco** [comment]
As @swcurran mentions you can restrict for equality like the following:

```
... restrictions = [
                  {
                      schema_name: "schema_name": "energy schema",
                      "attr::eval::value": eval_int,
                  },
              ];
```

You can do this for revealed attributes as well as predicates (as of indy-sdk 1.16, however to use this in a predicate you *also* have to reveal the actual value in a revealed attribute).

I'm not sure why your ZKP scenario didn't work, however I suspect the ZKP logic is only looking at one of your conditions.

**Comment by ianco** [comment]
> ... I suspect the ZKP logic is only looking at one of your conditions.

My Rust is a bit rusty but I think this line - building a hashmap of received predicates - only looks at one predicate per attribute:

https://github.com/hyperledger/indy-sdk/blob/master/libindy/src/services/anoncreds/verifier.rs#L52

**Comment by swcurran** [comment]
Interesting -- so multiple predicates are fine, just not multiple predicates of the same attribute (claim). That's reasonable.  Thanks, @ianco -- good information.

So that means you have to go to another solution for the "equals" -- as we have shared.

I'm going to close this issue while I'm here.  Please add any comments and reopen this issue as needed.
