### ISSUE TITLE
Support receiving messages of any minor version of any protocol

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1736]
Per [RFC 0003 Protocols](https://github.com/hyperledger/aries-rfcs/tree/main/concepts/0003-protocols#recipient-rules), any Aries agent should be able to handle all minor versions of a protocol.

Please update the protocol message handlers to be able to handle all incoming message messages as per the link above.  If ACA-Py supports a major version of a protocol, it should be able to receive a message for any minor version of that protocol and handle it appropriately -- based on the rules outlined in the link above.

For the most protocols, there is only one minor version of the protocol, and as such, the only change needed is to be able to handle a higher minor version number, and respond with a message using the minor version supported in ACA-Py. 

Where there are protocols with a major version that has multiple minor version numbers, add issues and separate PRs to support both versions of each defined protocol.

**Comment by swcurran** [comment]
@shaangill025 @andrewwhitehead -- it occurs to me this might already be supported.  Could one of you please take a look at the current state of ACA-Py with respect to this and add a comment?  If this is already supported, this can be closed with that comment.  If not, please add any thoughts you have of how to support this.

Thanks!

**Comment by andrewwhitehead** [comment]
We are meant to accept newer minor versions of any protocol. definition.py for out-of-band currently contains this (with `minimum_minor_version`):

```
versions = [
    {
        "major_version": 1,
        "minimum_minor_version": 0,
        "current_minor_version": 0,
        "path": "v1_0",
    }
]
```

I couldn't see any tests of the protocol registry that explicitly try to resolve a newer version that the minimum minor version, so we should add one and fix the resolution if there is an issue there.

**Comment by swcurran** [comment]
That's good news?

Who can grab this need to have a test?  Intrigued as to how you force this to happen in a unit test...

**Comment by shaangill025** [comment]
I looked into this yesterday, related to #1735 I found an issue when we have to use an existing connection [involving HandshakeReuse].
- Considering we have 2 agents, Alice [let's say v7.3.0, with 1.0 version specified in `message_types`] and Bob [with 1.1 version specified]
- Alice is initiating OOB invitation (public) and if there is no existing connection then the connection is created without any problem
- But if we repeat again it will try to reuse the connection so Bob will send `HanshakeReuse` message. The `message_type` for `HandshakeReuse` is imported (hard coded, 1.1) from `./out_of_band/v_1/message_types`.
- On Alice side, we get the following error:
```
2022-04-20 14:58:31,023 aries_cloudagent.core.conductor ERROR DON'T shutdown on TypeError argument of type 'NoneType' is not iterable
2022-04-20 14:58:31,023 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/core/dispatcher.py", line 142, in handle_message
    message = await self.make_message(inbound_message.payload)
  File "/home/indy/aries_cloudagent/core/dispatcher.py", line 234, in make_message
    message_cls = registry.resolve_message_class(message_type)
  File "/home/indy/aries_cloudagent/core/protocol_registry.py", line 170, in resolve_message_class
    return ClassLoader.load_class(msg_cls)
  File "/home/indy/aries_cloudagent/utils/classloader.py", line 97, in load_class
    if "." in class_name:
TypeError: argument of type 'NoneType' is not iterable
```

I have figured out a way to register `message_types` and `controllers` in `protocol_registry` dynamically based upon the `definitions.py`

For a single minor version, this will register both 1.0 and 1.1.
```
versions = [
    {
        "major_version": 1,
        "minimum_minor_version": 1,
        "current_minor_version": 1,
        "path": "v1_0",
    }
]
```
For multiple minor versions, this will register 1.0, 1.1, and 1.2.
```
versions = [
    {
        "major_version": 1,
        "minimum_minor_version": 1,
        "current_minor_version": 2,
        "path": "v1_0",
    }
]
```

As in the case of OOB for backward compatibility, I think the challenge will be to assign `message_type` for `AgentMessages` dynamically so that we use the same version as the initiating message.

**Comment by shaangill025** [comment]
> The error that Alice is reporting looks like a code bug, trying to resolve an empty class name maybe?

BOB
I tried with the following `definition.py` and `1.1` in `message_types` in OOB:
```
versions = [
    {
        "major_version": 1,
        "minimum_minor_version": 0,
        "current_minor_version": 1,
        "path": "v1_0",
    }
]
``` 
ALICE
Upon receiving `HandshakeReuse` message, at this [point](https://github.com/hyperledger/aries-cloudagent-python/blob/67dc094383aed4d5cf42c89ba64ff63267d6a3a8/aries_cloudagent/core/protocol_registry.py#L135), the message_type is `did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/out-of-band/1.1/handshake-reuse`. Since, this agent is v7.3.0, this message_type will not exist in `_typemap`, I think this is why the msg_cls is None.

> We don't want to set the minimum_minor_version to 1, as that would reject 1.0 messages.

I agree with your point

> We also want to accept messages with a minor version greater than the current_minor_version, so manually registering messages for every minor version is not an option either.

Sounds good, I think in that case if the initiating message version is not the same as the version specified in `message_types` then use the lower version in corresponding messages [like HandshakeReuse].

**Comment by andrewwhitehead** [comment]
Yes I believe the agent should handle all incoming messages as if they are using `current_minor_version`, and always respond with `current_minor_version`. If another agent is rejecting 1.1 because they only support 1.0, then that would be considered an error.

**Comment by swcurran** [comment]
I don't think that is right.  Shouldn't it be:

If the agent receives a message from an agent supporting a _lower_ then the current version, the agent should respond with the lower version and not use features of the current version.  If it receives a message of _higher_ or equal to the current version, it should respond with the current version.

I'm not sure what you mean by "If another agent is rejecting 1.1". Do you mean they reject it by sending a problem report?

**Comment by swcurran** [comment]
I think we can -- and certainly in the examples we have.  Take a look at Present Proof 2.0 to 2.1.  An agent that supports 2.1 must respond with a 2.0 message and logic if the other agent only supports 2.0.

I think we have to support all minor versions.

**Comment by andrewwhitehead** [comment]
For present-proof the `current_minor_version` is set to 0, so we always respond with a 2.0 message, even when the other party is sending 2.1. What you're describing is much more complicated, and I don't think it matches the protocol versioning rules: https://github.com/hyperledger/aries-rfcs/tree/main/concepts/0003-protocols#semver-rules-for-protocols

**Comment by swcurran** [comment]
Pretty sure that I have it right.  From the RFC:

`message types received with a minor version at or higher than the minimum supported and less than the current minor version are processed, ideally with a response using the same minor version of the received message`

There is wiggle room ("ideally") and we may not set "minimum supported" to 0, but I would think our goal should be to support all minor versions unless there is a good reason not to.  However, AFAIK, there are no existing cases where we have to address this.

I'm assuming for all protocol major versions where there is more than one minor version:

- We have the `minimum` as `0`
- `current` may be set to any of the minor versions.
- We can handle any higher than current minor versions.

Does that match your thinking or am I missing something?

**Comment by andrewwhitehead** [comment]
At the moment all the protocols we support have a minimum_minor_version of 0 except for introduction, which is 1.

I just don't see the benefit in adapting the response minor version to match the sender when by definition, they should accept and be able to handle any greater minor versions. In this case we would need to track the received message version somewhere, be sure to leave out the `accept` parameter if it is 0, and then serialize the message with 1.0 in the protocol identifier. At the moment serialize is just a method with no parameters, and each message type has a static protocol identifier, so it would take some refactoring to be able to do that. (We would need to update the serialization to support DIDComm v2 of course.)

**Comment by swcurran** [comment]
I think we are good on this issue and so I am closing.  @andrewwhitehead @shaangill025 -- if you think there is more to do on this, please let me know.  Thanks.
