### ISSUE TITLE
Which mobile agent framework is recommended to work with aca-py as the mediator agent?

### ISSUE THREAD

**Issue by github-account-0x00** [hyperledger/aries-cloudagent-python#1794]
I know this place is for issues but I'm having trouble finding a working open source mobile agent framework that integrates with iOS swift and android kotlin that can talk to aca-py as the mediator

**Comment by swcurran** [comment]
AFAIK, there are no open source Swift/Kotlin Aries mobile frameworks.  I know there are some that are proprietary, and there has been talk of some of those being made open source, but that hasn't happened yet.  Existing options are:

- React Native -- based on Aries Framework JavaScript (https://github.com/hyperledger/aries-mobile-agent-react-native)
- Xamarin - based on Aries Framework .NET (https://github.com/hyperledger/aries-mobileagent-xamarin)
- Findy has a cloud-based wallet with a mobile UI

If you are not planning to use AnonCreds verifiable credential format and Indy ledgers, you can look at Aries Framework Go, which might have a relatively easy path to native mobile wallets.  But I'm not aware of any mobile capabilities in that.

Hope that helps.  Feel free to reopen and/or ask more specific questions.

**Comment by github-account-0x00** [comment]
Do you have any experience in building the react native or xamarin code? 
I tried building the react native but experienced some issues with it which I highlighted here:
https://github.com/hyperledger/aries-mobile-agent-react-native/issues/347

Also, what is your opinion of aries vcx?

**Comment by github-account-0x00** [comment]
For the xamarin agent, I need to get indy-xamarin-libs.zip from https://hyperledger-org.bintray.com/aries/  but I keep getting bad gateway, do you have the files by any chance?

**Comment by swcurran** [comment]
Our team is working heavily on AFJ/React Native and just recently started using it (sort of) in the wild - e.g. with real users. The team has created an excellent build/publish process that allows for merging the https://github.com/hyperledger/aries-mobile-agent-react-native code with ours to produce a publishable artifact. That allows for changes to be made in the right place (e.g. in Bifold or our instance), maximizing the collaboration.  There are others doing that, still others that have done a "fork and forget" with the aries-mobile-agent-react-native repo.  It absolutely can be built and works pretty nicely!

The Aries MAX (Xamarin) has a smaller user base and is evolving slower, held up mostly because many devs aren't a fan of Xamarin. 

I know that there is a lot of activity going on with Aries VCX, and the team behind it is excellent.  That said, I don't know that much about using it as the basis for a mobile agent. I think (not certain) that a variation of the code base is used as the foundation of the Evernym wallet, but don't know how much cross-over there is.

**Comment by darapich92** [comment]
Hi @swcurran, I saw BC-Mobile-Wallet `https://github.com/bcgov/bc-wallet-mobile` on github. do you think that it provides functionalities like aries mobile agent react native?

**Comment by swcurran** [comment]
BC Wallet is built on top of Aries Mobile Agent React Native, so definitely includes all of the features. It also shows how to build on top of Aries Mobile Agent React Native without forking the wallet and making it hard to both get updates from, and contribute back to, Aries Mobile Agent React Native. Being able to do that is a big win for everyone!

**Comment by darapich92** [comment]
@swcurran thank you very much for the information.
