### ISSUE TITLE
On upgrade to 0.7.4, multiwallet tokens don't work without iat

### ISSUE THREAD

**Issue by frostyfrog** [hyperledger/aries-cloudagent-python#1889]
For jwt tokens that have been created without the iat field, they will no longer be considered valid and the profile cannot be retrieved. The offending code is located here:
https://github.com/hyperledger/aries-cloudagent-python/blob/dbe0f09e2c89d2da2da744d1d751da0dd40498ad/aries_cloudagent/multitenant/base.py#L395-L411

[This commit](https://github.com/frostyfrog/aries-cloudagent-python/commit/dbc22078892edf1eaa7cf93a8809695d4c9aabcc) should resolve the issue, however. I believe that it goes against the spirit of the original code.

**Comment by swcurran** [comment]
Let's talk about this on the ACA-Pug call tomorrow. I'd like to understand the importance of this -- sounds bad...

**Comment by swcurran** [comment]
This was discussed at the ACA-Pug meeting, and it was pointed out that this was expected behaviour as part of this change -- [PR \#1725 comment](https://github.com/hyperledger/aries-cloudagent-python/pull/1725#issuecomment-1096172144).

Debatable whether this is a breaking change, but we've added a warning to the [Changelog for 0.7.4](https://github.com/hyperledger/aries-cloudagent-python/blob/main/CHANGELOG.md#june-30-2022).

The proposed change (above) would remove the impact of the #1725 change, which is not helpful.

Closing this issue.
