### ISSUE TITLE
Exception: Error registering DID when running ./run_demo faber

### ISSUE THREAD

**Issue by twshelton** [hyperledger/aries-cloudagent-python#1923]
I'm following the docker demo instructions, have the VON network running and when I attempt to `./run_demo faber`, I get the attached error.  Any thoughts on how to get around?  I'm running an MacOS M1 processor if that helps.

![Screen Shot 2022-08-31 at 2 02 13 PM](https://user-images.githubusercontent.com/61970/187748607-50716f34-8d3b-481a-b43e-21d74ab71cf8.png)

**Comment by ianco** [comment]
Error 503 is service unavailable.  The agent is trying to register a DID on the ledger, are you running a local ledger?

**Comment by twshelton** [comment]
I'm following the directions in the repo.  The VON ledger is running and
accessible.  Is something else required?

Thanks,
Thomas

**Comment by ianco** [comment]
Can you open http://localhost:9000 in a browser?

**Comment by twshelton** [comment]
Yes that works for me.  I see the VON landing page.

Thomas

**Comment by twshelton** [comment]
See attached.

**Comment by ianco** [comment]
Hmm what platform are you running on?

By default (I think) we use "host.docker.internal" as the host name for the ledger nodes, some platforms don't support this.  (If you open http://localhost:9000/genesis in a browser it will show the ledger pool transactions, which contain the host name)

If "host.docker.internal" doesn't work on your platform you can use the IP instead - you need to use the IP that is used internally by the docker network, not your local machine IP.  You start von-network as `./manage start <ip> --logs`, and then you need to pass the ledger url to faber, I think `LEDGER_URL=http://<ip>:8000 ./run_demo faber` (note that 8000 is the internal port within docker but it is exposed as 9000)

Anyways this is just off the top of my head, if you poke around the von-network repo there should be some docs in there

Alternately you can just use an external ledger rather than running your own von-network:

`LEDGER_URL=http://test.bcovrin.vonx.io ./run_demo faber`

**Comment by swcurran** [comment]
Weird that the error is about "endorser_agent".  I just ran the demo on Linux with a local von-network and all went well. We use these agents on all the integration tests, so the issue is likely something local.

**Comment by twshelton** [comment]
It is a Mac M1 and I’ve seen little interesting errors with Docker a lot.
I’ll try the external network and see how it goes.

Thanks guys!

Thomas

**Comment by ianco** [comment]
> Weird that the error is about "endorser_agent". I just ran the demo on Linux with a local von-network and all went well. We use these agents on all the integration tests, so the issue is likely something local.

The "endorser_agent" is a red herring.  The error is registering the faber public did on the ledger.  When this fails, the faber controller tries to shut down all the agents - since there is no endorser in this case you get the "no attribute 'endorser_agent'" error (which is another issue although a minor one).

**Comment by ianco** [comment]
> It is a Mac M1 and I’ve seen little interesting errors with Docker a lot. I’ll try the external network and see how it goes. Thanks guys! Thomas

I've heard of other issues with Mac M1 but I can't help with that :-(

(Maybe @swcurran will pitch in for a new Mac M1 for me)
