### ISSUE TITLE
Webhook documentation

### ISSUE THREAD

**Issue by Alexis-Falquier** [hyperledger/aries-cloudagent-python#194]
Is there documentation of all the different webhook URL's and their payloads? Currently in order to figure it out I have been testing each call.

**Comment by swcurran** [comment]
We're going to figure out how best to document this. There is only one
Webhook that fires on events in the agent. I suspect the answer is to look
at the data models for the incoming messages, but we'll confirm that.  The
messages are in the `messaging` folder under `aries-cloudagent`.

More to come on this one.  Thanks for the reminder.

**Comment by Alexis-Falquier** [comment]
Sounds good Ill keep an eye out, thanks!

**Comment by swcurran** [comment]
Documentation has been added [here](https://github.com/hyperledger/aries-cloudagent-python/blob/master/AdminAPI.md#administration-api-webhooks) to get started with the webhook interface.

Closing this issue.  Since it is documentation it can always be improved, so we welcome further PRs on this and suggestions on more useful ways to document this.
