### ISSUE TITLE
how tails files used and why tails server url public

### ISSUE THREAD

**Issue by abhimin** [hyperledger/aries-cloudagent-python#2003]
I set the tailsserver and revoking the credential.but need some info on how the tails file in storage path used and why tailsserver url should be public.
Is it safe to expose tails files to Internet and who are interacting with tails server.

Please share some insights on this.

**Comment by swcurran** [comment]
A good overview of the current AnonCreds revocation scheme is described here: https://github.com/hyperledger/indy-hipe/tree/main/text/0011-cred-revocation

The tails file is public because the holders of AnonCreds verifiable credentials must be able to download them -- basically they need to be on a web-accessible file service. For holders on mobile devices, that service must be HTTPS, or the OS won't allow the app to download them.

Those are the requirments for the current version of revocation. 

Closing this for tracking purposes, but please ask additional questions or re-open if appropriate.
