### ISSUE TITLE
How to use tag arg-file when with agent docker image

### ISSUE THREAD

**Issue by abhimin** [hyperledger/aries-cloudagent-python#2025]
I'm using docker run  agent image acapy start --arg-file ./local.yaml  but not able to start acapy

**Comment by ianco** [comment]
When you're running in Docker you need to either copy your config file into the docker image, or else mount the directory containing your config file so that it's accessible within docker.

There's an example that shows how to do this:  https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/docker/docker-compose.yml

(This is for a multi-ledger config file, but the principle is the same.  The example uses docker-compose but you can do the same thing running docker from the command line)
