### ISSUE TITLE
How to create or use private schema in wallet database using postgres

### ISSUE THREAD

**Issue by abhimin** [hyperledger/aries-cloudagent-python#2043]
Trying to deploy agent with postgres wallet storage and wallet type as askar but it is using public schema.
Initially created a database with admin user and tables by running acapy agent and then trying to use this dB with same app user after revoking admin access.
Here tables are created in public schema .please help on how to create and access tables in private schema within database

**Comment by abhimin** [comment]
@swcurran can you provide info on this

**Comment by ianco** [comment]
You provide the following parameters to aca-py on startup:

```
            --wallet-storage-type '${ACAPY_AUTHOR_WALLET_STORAGE_TYPE}' \
            --wallet-storage-config '{\"url\":\"${AUTHOR_WALLET_POSTGRESQL_HOST}:5432\",\"max_connections\":5,\"wallet_scheme\":\"MultiWalletSingleTable\"}' \
            --wallet-storage-creds '{\"account\":\"${AUTHOR_WALLET_POSTGRESQL_USER}\",\"password\":\"${AUTHOR_WALLET_POSTGRESQL_PASSWORD}\",\"admin_account\":\"${AUTHOR_WALLET_POSTGRESQL_USER}\",\"admin_password\":\"${AUTHOR_WALLET_POSTGRESQL_PASSWORD}\"}' \
```

When provisioning the wallet database, the `admin_account` and `admin_password` must specify a database user with privileges to create the database and tables for the wallet.  (The `account` and `password` are used to access the wallet once is created.)

If the database already exists (in some scenarios the dba has to create the database in advance) it must be empty - aca-py will create and populate any tables and other db objects it needs.

At least that's how indy-sdk works, @andrewwhitehead can confirm if this is also true for askar.

**Comment by abhimin** [comment]
@andrewwhitehead 
Hi Andrew-any updates on how to create tables in private schema within existed postgres database using askar.

**Comment by ianco** [comment]
> we would also prefer to get the database initialization commands as database scripts for creation everything needed in database

That won't work with an Indy wallet (and I suspect Askar as well) because aca-py doesn't just create the tables when it creates the wallet, it populates them with encryption key information as well (and possibly other info, I don't know the low-level details).  It's possible that with changes to the low-level sdk's (Indy and/or Askar) this might be able to work ...

However, there is a command avalabile to "provision" the wallet using aca-py - there is an example of how to ru this command here:  https://github.com/bcgov/aries-vcr/blob/main/docker/docker-compose.yml#L143

So, you could run this command separately (manually, or however you choose) - this is the command that requires the "admin" id.  And then in your regular aca-py script, you only need to provide the "regular" postgres id.

At least that is what is supported now, if you want to manually create all the tables and other db objects in advance, and then have aca-py to be able to detect this state on startup, you'd need to do some updates to the low-level libraries.

**Comment by darapich92** [comment]
Hello everyone, I ran the command of aca-py start but I received an error "OSError: libindystrgpostgres.so: cannot open shared object file: No such file or directory". Could you help me with it? thank you very much!
