### ISSUE TITLE
investigate connection protocol problems

### ISSUE THREAD

**Issue by nrempel** [hyperledger/aries-cloudagent-python#216]
reply message sent before other agent has finished setting up the connection

**Comment by swcurran** [comment]
Can we add some details about this?  What's the issue?  What's the expected result?  What's the priority of this vs. other work?

**Comment by nrempel** [comment]
@andrewwhitehead can you reliably reproduce this? If so, can you add steps to reproduce here?

**Comment by andrewwhitehead** [comment]
This was happening in the IIWBook demo due to the way the webhooks and admin API interact. The controller would receive a webhook indicating that the connection had entered the `response` state (not `active`, as the mobile client never sends an acknowledgement message) and would immediately send a proof request on that connection. The problem is that the webhook is sent as the connection record is persisted, but could be processed and responded to before the connection response message hits the delivery queue, which confused the mobile app when they arrived out of order.

**Comment by swcurran** [comment]
Ah...hence the intermittent success in running the demo.  Can this be closed, referencing a commit?

**Comment by andrewwhitehead** [comment]
@swcurran We worked around it by adding a delay. A better solution might be to add an explicit acknowledgement message in DID-Exchange and then move the logic to the 'active' phase of the connection.

**Comment by andrewwhitehead** [comment]
Worked around the issue. In future we may send feature-discovery as the first message, which has fewer requirements and would indicate which credential issuance protocol to use.
