### ISSUE TITLE
default_version_upgrade_config.yml file missing from aca-py release

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#2178]
`default_version_upgrade_config.yml` is missing from aca-py python release - this file is required to run the `aca-py upgrade` command.
 
See this issue:  https://github.com/bcgov/openshift-aries-mediator-service/issues/25

**Comment by WadeBarnes** [comment]
The file is in the correct location and contains the correct content.  It just needs to be included in the release.

I did find it strange that you can only specify versions that are explicitly listed in the config file and that when upgrading to `v0.8.0` you have to specify `--from-version=v0.8.0` rather than indicating the version you're actually upgrading from.

**Comment by WadeBarnes** [comment]
The file existing in the source code; https://github.com/hyperledger/aries-cloudagent-python/tree/main/aries_cloudagent/commands

But is not included in the PyPi distributions; https://github.com/bcgov/openshift-aries-mediator-service/issues/25#issuecomment-1481453249

and therefore is not installed on the images.

**Comment by swcurran** [comment]
OK — some somewhere there is a manifest of things to include in the PyPi release.  I’ll see what I can figure out.

**Comment by swcurran** [comment]
But that means we need to do a 0.8.1 immediately, right?

**Comment by swcurran** [comment]
I can’t see how to add it to the package. AFAIK, the PyPi release should pickup everything in `aries_cloudagent`, which should include that file.

@ianco — if you know what update is needed, please do it. If not, I’ll get someone else to investigate.  I’m assuming this is trivial.
