### ISSUE TITLE
Support OpenID4VCs in ACA-Py

### ISSUE THREAD

**Issue by loicsikidi** [hyperledger/aries-cloudagent-python#2182]
Hi,

First and foremost thank you for the incredible amount of works that you have done in that area 🚀 .

Do you plan to implement the full implementation of [OpenID for Verifiable Credentials](https://openid.net/openid4vc/) in a near future?

* [OpenID for Verifiable Credential Issuance (OID4VCI)](https://openid.bitbucket.io/connect/openid-4-verifiable-credential-issuance-1_0.html)
* [OpenID for Verifiable Presentations (OID4VCI)](https://openid.bitbucket.io/connect/openid-4-verifiable-presentations-1_0.html)
* [Self-Issued OpenID Provider v2 (SIOPv2)](https://openid.bitbucket.io/connect/openid-connect-self-issued-v2-1_0.html)

**Comment by swcurran** [comment]
Sorry for the slow answer.  Work has started on this in Aries Framework JavaScript (see this [PR 1384](https://github.com/hyperledger/aries-framework-javascript/pull/1384). We’re planning on learning from that and then seeing how OpenID4VCs fits into the Aries frameworks in general and ACA-Py specifically.  We’ve been talking with the OpenID folks since the announced their protocols.  We expect to learn more and discuss ideas for adding OpenID4VCs to Aries at the upcoming IIW later this month.

More to come.  If you have some contributions to make in this area, please let us know.

**Comment by LoicSikidi** [comment]
Hi,

(sorry also for the lack of velocity...).

Great news! I'll check the PR 👀 .

Anyway, I am motivated to be a contributor on this topic if the project need resources.

There is a lot of stuff to do in this area 🚀 .

**Comment by steatcal** [comment]
@swcurran  -has there been any further discussion for support in ACA-Py. If for sure would be tremendously helpful if it was dual-stack!

**Comment by swcurran** [comment]
Some discussion, but no one has (AFAIK) built anything.  There hasn’t been a PR.  From a BC Gov perspective, we’re looking forward to seeing what happens in AFJ with the support they have added — how it gets used.  And continuing on with the many other things that we’re doing :-).

**Comment by swcurran** [comment]
Discussed on the ACA-Pug call 2023.08.08.  Noted in the call:

A possible design is to make it a companion service that calls into ACA-Py vs. within ACA-Py -- much like we do today in [vc-authn-oidc](https://github.com/bcgov/vc-authn-oidc). There is a requirement for additional public endpoints beyond the DIDComm endpoint, and so perhaps those could be in a separate service calling ACA-Py endpoints for preparing (SD-)JWT credentials – similar to the JSON-LD endpoints we have today – sign/verify.

Another alternative might be a – plugin, so that there can be a tighter integration for calling ACA-Py utility functions directly, but still a separation from the core features of ACA-Py.

And of course, it could also be a feature added to ACA-Py directly.

**Comment by swcurran** [comment]
Plugin available in the plugins repo -- https://plugins.aca-py.org
