### ISSUE TITLE
Investigate the handling of "replacement_id" in ACA-Py

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2218]
Aries [RFC 0453 Issue Credential V2.0](https://github.com/hyperledger/aries-rfcs/tree/main/features/0453-issue-credential-v2) adds support for the `replacement_id` data element in the `offer` and `issue` messages.  The intent of the item is for an issuer to give the holder an ID for a credential such that if the holder sees that ID on a new issue, the issuer is indicating the previous credential has been revoked and replaced with the new credential.  This enables, for example, an issuer issuing several credentials of the same type to a holder (for example, a university issuing several degree credentials to a student) can, when replacing one of them, let the holder knows which one was replaced.  The ID is defined by the issuer, and the holder should not share the ID to anyone else.

There appears to be some references to `replacement_id` as being supported in the V2.0 implementation of ACA-Py (e.g. in [openapi.json](https://github.com/hyperledger/aries-cloudagent-python/blob/d82e45080553069d133e12155526916c2d5beeb2/open-api/openapi.json#L10091) and in the [issue credential v2.0 manager](https://github.com/hyperledger/aries-cloudagent-python/blob/d82e45080553069d133e12155526916c2d5beeb2/aries_cloudagent/protocols/issue_credential/v2_0/manager.py#L203). However, when I run the Alice-Faber demo and add the `replacement_id` element in using the `/send` endpoint, the ID is not saved by the holder (Alice).  I'm not sure if that is a controller issue or if the implementation of `replacement_id` is incomplete.

Here are things to investigate:

- Does the issue credential v2.0 `/send` endpoint implement the `replacement_id` capability?
- Does a holder being issued a `replacement_id` store that data element with the credential?  Is that an ACA-Py capability, or is it up to the controller?
   - I think it is up to ACA-Py to store it if present, and up to the controller to do anything with it on receipt.
   - Further, I think if it is stored, there likely needs to be a tag created so that the ID can be looked up on receiving new credentials.
- Why does the item not show up in the Swagger UI?

**Comment by swcurran** [comment]
@usingtechnology — please take a look at this one next. We are looking to have this support available for the Person credential.

**Comment by swcurran** [comment]
@usingtechnology — let me know if there is enough context here for the issue.

**Comment by usingtechnology** [comment]
Ok, initial findings are that the value is included as a field in `cred_offer` and `cred_issue` objects. They are only present in the response schemas. So you can see it in the response bodies in OpenAPI. You cannot see it in the requests because it isn't there in the code. Also, there are parameters to the pass a value in (to set it), but nowhere in the code is that parameter ever set. 

It is not saved with the credential, it would appear that the holder would examine the value during the exchange and deal with it appropriately. So, if exchange is not preserved then nothing saved that would say which credential replaced a previous one.

Short answer is that it is 1/2 implemented - we have it stored and returned in the exchange, but no way to set it via the API.
