### ISSUE TITLE
Provide nightly builds for ACA-Py 

### ISSUE THREAD

**Issue by usingtechnology** [hyperledger/aries-cloudagent-python#2250]
For developers that require access to bug fixes, we should provide nightly builds (or build on merge to main?) of the ACA-Py images.

Investigate if we can leverage a nightly build in AATH or other testing situations.

**Comment by swcurran** [comment]
@gavinok

**Comment by WadeBarnes** [comment]
Nightly builds would be sufficient.  Building on merge to main would cause unnecessary strain on Hyperledger's GitHub actions runner time allotments.

The nightly builds should incorporate the nightly test runs and only build/publish on success.  The workflow should only run if there are changes to the repo since the previous run, there is no point in wasting precious runner time.

The workflows you want to look at are:
- https://github.com/hyperledger/aries-cloudagent-python/blob/main/.github/workflows/nightly-tests.yml

- https://github.com/hyperledger/aries-cloudagent-python/blob/main/.github/workflows/publish.yml
  - To publish a nightly version of the image.  You'll need to update the workflow to tag the image appropriately; e.g. `nightly`.

-  https://github.com/hyperledger/aries-cloudagent-python/blob/main/.github/workflows/pythonpublish.yml
  - To publish a nightly python package, if we decide to do that.  **This requires some additional thought and investigation due to the fact we'd be publishing more frequently to PyPi and may need to perform cleanup.**

Ignore https://github.com/hyperledger/aries-cloudagent-python/blob/main/.github/workflows/publish-indy.yml, because we're dropping support for the indy-sdk releases and this workflow will go away.
