### ISSUE TITLE
Pagination on created schemas and cred defs?

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2373]
See: https://github.com/hyperledger/aries-cloudagent-python/blob/anoncreds-rs/aries_cloudagent/anoncreds/issuer.py#L232-L255
And: https://github.com/hyperledger/aries-cloudagent-python/blob/anoncreds-rs/aries_cloudagent/anoncreds/issuer.py#L417-L446

This is similar in behavior to the current interface but as you can see it is using `fetch_all` to retrieve all of the matching records. In the event your issuer has created lots of schemas/cred defs, this might be a slow operation. Should it use pagination?

**Comment by dbluhm** [comment]
Perhaps it is best to just use the other values to narrow the results rather than to paginate?

**Comment by genaris** [comment]
Are you using pagination for other kind of records in ACA-Py? We had recently a discussion regarding this in an AFJ call and we figured out that, even if it's certainly possible to add offset and limit, special care must be taken in case new records are added between calls. 

An issue we have is about sorting: [it seems](https://github.com/hyperledger/indy-sdk/issues/2431) that Indy's WQL was not meant to store a massive amount of data (and possibly Askar inherited this design constraints as well). For server deployments like ACA-Py it's a bit tricky because we would probably like to sort records by creation date or last activity date or whatever, and this will not be possible if using encrypted tags.

**Comment by swcurran** [comment]
Closing in favor of #3001
