### ISSUE TITLE
Nightly build/test - add support for running the tests inside containers

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/aries-cloudagent-python#2457]
The nightly tests are run in a matrix of OS and Python version.  The test workflows are configured to execute directly on runners of the given OS.

Consider adding support for running the tests inside docker containers.  This would allow us to better test the images before they are published.  This would also open the door to test using a mix of existing and newer images versions.  In this scenario the Dockerfiles would be updated to include the OS definition as well as the Python version (currently supported) as build parameters.  We would then be able to test on a matrix such as [slim-bullseye, slim-bookworm], [3.9, 3.10], for example.

**Comment by dbluhm** [comment]
Good points; I actually deliberately swapped things over from running in a container at least partially for faster run times but that would be far less important for nightly testing vs PR tests. This is probably much less significant now that Indy isn't in the mix though since a lot of the time was build time.

**Comment by WadeBarnes** [comment]
The extra build time needed for the image(s) is a consideration, it will slow things down a fair amount.

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
