### ISSUE TITLE
Feature Request: Hot swapping wallets without restarting acapy

### ISSUE THREAD

**Issue by Brownie79** [hyperledger/aries-cloudagent-python#247]
Building scalable acapy agents requires a way to hot swap wallets without needing to restart the agent (which currently has a six second startup time).

**Comment by Alexis-Falquier** [comment]
^ second this

**Comment by swcurran** [comment]
Not quite sure what the use case is for this.  Could you explain a bit about what is needed?  That will better inform what is needed.

@andrewwhitehead @ianco - heads up on this request.  What changes do we need to make to support the (to be received :-) ) use cases.

**Comment by Alexis-Falquier** [comment]
We are building a cloud custody solution which manages multiple wallets using aca-py.  Since aca-py is built to handle one wallet at a time, a way in which to tell aca-py to switch context from one wallet to another without the need to fully stop the agent and start it up again as the other wallet would be massively useful as scaling is currently very difficult.

**Comment by nrempel** [comment]
We chose to build aca-py in such a way that there is always a 1:1 relationship between an identity controller (wallet) and an agent.

For an agenc**y** (multiple controllers) scenario, we envision an agent for each controller and a routing agent in front of them to act as the domain endpoint.

Note that this doesn't necessarily mean that the database cannot be multi-tenant since wallet and storage providers in aca-py could  point at  the same database if needed.

**Comment by Alexis-Falquier** [comment]
@ianco I agree context switching would be great for our use case as it is more scalable. Currently the handler I built is pretty much what @nrempel described for an agency. It sets up the aca-py agent with its incoming endpoint to be the handler and gives context to which wallet the call is for and forwards it to the correct aca-py agent if its running or starts it up again if its not running. This does not seem massively scalable as in a case where the agency handles thousands of wallets, a 1:1 relationship means you need to have an agent for each, where as context switching would allow for much less agents to handle the same amount of wallets.

**Comment by swcurran** [comment]
The questions I would have are

- How are you managing the encryption key per wallet (or more precisely I think - per identity owner)?
- How do you want to handle multi-tenancy separation?

On the former, how do you get the keys to encrypt and decypt the data per wallet?

On the latter point, could you have a single database with all the data in it, and a wallet-id flag that filters requests for the wallet of interest?  This is a "virtual wallet" mechanism that we have used before.  That might be a problem if for the multi-tenancy you really want all the wallets in separate databases. That way you don't have to single-thread requests in order to have the same wallet open throughout the processing of a request.

The other challenge I see is how get the right wallet-context with every event - incoming messages from agents and admin API messages. Likely you can do that based on the 
incoming verkey for a message (verkey to wallet mapping), but not sure how you would do that with the Admin API.  What is needed associated with all Admin messages to indicate the wallet context?

**Comment by Alexis-Falquier** [comment]
For the second question, we would rather not do multi-tenancy but rather context switching. The reason being the ability to move / migrate the wallet. e.g. if the user whose given us custody of the wallet wants to download it to be used elsewhere or to retrieve their information from us. we need to be able to do that, correct me if I am wrong, multi-tenancy would make this problematic.

for the first question, we havnt fully decided on but our first thoughts are creating a random key and encrypting it. it is only decrypted when passed on the first creation of the aca-py agent or when it needs to be started again (for context the handling of this and where the aca-py agent lives is all in a closed system and stored in an encrypted manner). The way it knows which key is the correct one is through the context of who is making the call, which the handler will know. How it knows also addresses the last question.

How we do it:

For agent messaging:
The way we have built the handler-agent relationship is such that we set the receiving endpoint for the agent (i.e the SSI-Agent-Wire messages) to not go straight to the aca-py agent but rather the handler. In this endpoint is an identifier query parameter which the handler can retrieve and map that to the correct wallet. From this it then forwards the ssi-agent-wire message to the correct instance of aca-py. 

For admin API:
Our handler is also set up as an API that whenever a call is made to do an action such as creating an invitation, the wallet context is given in the call (i.e wallet name). so it can then make the admin api call on the correct aca-py agent. 

How it could work on aca-py

if context switching is implemented, when initiating aca-py a flag can be set saying whether you want context switching, if not it acts as it does now. if yes:

Admin API:
Similar to what we are doing, it could be that 'wallet_name' is passed as a parameter alongside admin-api calls this giving it the context in which to act.

Agent messages:
One possible way is ssi-agent-wire messages could be passed straight to the aca-py agent and as you mentioned the context is made through verkey-wallet mappings

Let me know you want me to clarify any of this. Thanks!

**Comment by swcurran** [comment]
We talked about this a lot with Evernym's architects and some at the Aries Connectathon.  We think the solution for this is most likely to have a wallet-id to the context of the KMS/storage APISs that might:

- filter on an extra column in the data store to limit results to an individual "wallet" in the database.
- prefix table names that are referenced to access the data for an individual wallet; on registering a wallet, add new tables for that wallet.
- add a new database per wallet and access that database on calls to the wallet.

Presumably there would be a separate encryption keypair per wallet, and part of accessing the wallet would be to get and use that keypair.

My $0.02CDN is that the first option is likely the best, as it most in line with "common" database designs.  It does put all of the data for the all the wallets into the same tables/context.

Note that for the handling of extracting wallets and providing them to the users when needed to hold themselves, I would think that a standard wallet export/input mechanism would be used, and that the storage format within (for example) an ACA-Py instance would not be relevant.  It would just have to support an interoperable import/export at the Aries level.

Regardless, this issue is not really an ACA-Py issue, but rather one that will have to be addressed at the Aries KMS and protected storage layer.

I'm going to close this issue as out of scope for now. That said, if anyone would like to get together to discuss different approaches because a solution is needed prior to the Aries-based solutions are ready, we'd be happy to do that.  As well, we would definitely like to hear about what approaches are taken if this is implemented by another team.
