### ISSUE TITLE
Aca-py storage / migration question

### ISSUE THREAD

**Issue by Alexis-Falquier** [hyperledger/aries-cloudagent-python#251]
I was wondering where the meta information (i.e connection-id's, credential-exchange-id's etc.) is stored (using wallet type and storage type indy)? This is useful in case one would want to migrate the wallet from one server to another and still use aca-py, that way when starting aca-py in the new server it still has all the information to act correctly. 

Would simply moving the wallet file in home/user/.indy_client/wallet/wallet_x suffice? or is there another file that aca-py points to that needs to be migrated as well?

**Comment by swcurran** [comment]
Right now, ACA-Py uses the Indy non-secrets storage for the metadata - connections and protocol state. There are startup options for what implementation that you want to use via the "storage" module. Currently basic and Indy storage can be used, and for Indy, either the SQLite or Postgres options - the same options that are available for the secrets storage.

I'm not certain of the details, but if you use the Indy SQLite storage, I think it does get stored in that location.  Whether you can move it around at the file level vs. using SQLite tools is not something I know.  We're better versed in the use of Postgres for storage, and we only use database tools for manipulation, because of the risk of corruption.

**Comment by swcurran** [comment]
Closing this issue as answered.


Note that in the future implementation of the Indy-sdk/aries-sdk, storage will be separated into the KMS for keys and keys metadata, and a protected storage mechanism. Things like credentials and protocol state objects will go in the protected storage mechanism. It's possible that such a storage mechanism will make use of efforts around Identity Hubs (DIF), replicated storage, and EDV (Encrypted Data Vaults) from Digital Bazaar.  More to come on that as we get deeper into the break up of the indy-sdk.
