### ISSUE TITLE
Unexpected state of (orphaned) connection when request is rejected

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/aries-cloudagent-python#2530]
During the investigation of https://github.com/hyperledger/aries-cloudagent-python/issues/2528, connection requests from the issuer where rejected by the endorser or caused errors on the endorser side.  This was either not communicated back to the issuer or the issuer was not doing anything with the information - I was unable to confirm whether the expected problem report was generated and received by the issuer or not generated at all.

As a result the issuer (in this case) had a pending connection that was essentially orphaned. I would expect the request failure would be communicated so the connection record could be updated/deleted to indicate it was rejected.

**Comment by usingtechnology** [comment]
more context here... is this didexchange protocol or connection protocol?
i will investigate both but would prefer to concentrate on the actual case.

one thing in preliminary testing (using connection protocol) is if the error happens too early in the exchange then there is no ability to deliver a message back.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/workspaces/aries-cloudagent-python/aries_cloudagent/core/dispatcher.py", line 257, in handle_message
    await handler(context, responder)
  File "/workspaces/aries-cloudagent-python/aries_cloudagent/protocols/connections/v1_0/handlers/connection_request_handler.py", line 67, in handle
    await responder.send_reply(
  File "/workspaces/aries-cloudagent-python/aries_cloudagent/messaging/responder.py", line 140, in send_reply
    return await self.send_outbound(
  File "/workspaces/aries-cloudagent-python/aries_cloudagent/core/dispatcher.py", line 393, in send_outbound
    raise RuntimeError(
RuntimeError: Connection ef511b8f-3a6f-465e-a5ab-3a0198ee6ac9 is not ready which is required for sending outbound message 9f57fa94-43ed-4720-9a49-dea008d5dee5 of type connections/1.0/problem_report.
```

**Comment by WadeBarnes** [comment]
Only details I have at this point are in the linked issue.

**Comment by usingtechnology** [comment]
thanks.
i decided to follow the approach that I think would best simulate the flow with an endorser and report back.

- agent (endorser) has a public did
- agent (issuer or other) requests connection with endorser (`didexchange/create-request`)
- endorser reviews request and accepts it (`/didexchange/{connection_id}/accept-request`)
- connections are both `active`

I am not worrying about setting the metadata for endorsement, just the flow and where it could break down.

**Comment by usingtechnology** [comment]
Adding issue #2598. Fixing this doesn't fix everything but would be one step closer. I think the biggest obstacle in all of this is a connection needing to be far enough along the process to even have a Problem Report delivered.  That being said, if it is possible to deliver then we should and it does appear that the receiver does nothing with the report... that can/will change.

More to come...

**Comment by usingtechnology** [comment]
OK, further update here...
We can do some better handling by putting in an explicit ConnectionProblemReport handler and not defaulting to the ProblemReportHandler. That will allow us to set to abandoned, same as in the DIDExchange.

Working through this has uncovered myriad issues. None of which are huge but should all be addressed. Mostly it is the exception error classes are not consistent and will not work down the stack as expected. So I think some of the errors we think are getting handled are just getting swallowed up because they raise other errors. For instance, ConnectionManager errors need an error code  that in turn gets used as the ConnectionProblemReport problem_code. Now the problem_code has to be one of a specified ENUM but the ConnectionManagerErrors are just using random strings. So that will never work.

Also, maybe everyone knows this... connections (connection protocol) do not become active unless `auto-ping-connections` configuration is true. Did we all know this? There is no complete conversation/handlers. Maybe that is the protocol that once a connection is in `response` it is good to use. Anyway, I thought it was strange. Basically sending an auto ping kicks off the conductor and dispatcher to determine how to handle the message. In the course of that resolution it determines the associated connection, resolving that connection hits a piece of logic that sets the connection active if it is in a response state.

As stated, I will add some related issues as I don't think I have time to tackle all of it. I do have an example PR that I can push to show the new ConnectionProblemReport handler that will (when reached properly) set a connection to abandoned.

**Comment by usingtechnology** [comment]
Added another issue that needs to be addressed before we have an effective problem report handler. See #2599
