### ISSUE TITLE
Enable the "emit-did-peer..." startup options to be tenant specific

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2724]
We would like to see the new ability to emit DID Peer connections to tenant specific, so that we can experiment with enabling connection reuse.

**Comment by swcurran** [comment]
@esune , @loneil — what is the effort to do this?  Are there instructions on how this is done?

**Comment by esune** [comment]
[This PR](https://github.com/hyperledger/aries-cloudagent-python/pull/2233) has the changes that relate to per-tenant settings.
At minimum, we would extend the settings to be included/supported in the list that currently holds which settings can be "tenantized". We could also look at cleaning-up a bit that list (which is actually currently two lists) so that more settings are supported out-of-the-box without changes (probably a slightly bigger change).

**Comment by swcurran** [comment]
So the steps are:

- update the Multitenancy.md documentation to add the item tot he list
- update the admin/routes.py to add the item to the two lists

Sound right?

**Comment by esune** [comment]
Yes, that sounds about right if we just want to add this flag to the list without extra refactoring.
