### ISSUE TITLE
Can an application use the Aries Cloud Agent API to fetch all existing schemas from the ledger?

### ISSUE THREAD

**Issue by securedimensions** [hyperledger/aries-cloudagent-python#2837]
An application (business logic) can issue credentials once an existing schema is registered as a credential definition. To do this, it is sufficient to know the schema identifier:

```JSON
{
  "revocation_registry_size": 1000,
  "schema_id": "WgWxqztrNooG92RXvxSTWv:2:schema_name:1.0",
  "support_revocation": true,
  "tag": "default"
}
```

In the case where the business logic likes to use a schema identifier that does not exist in the agent's own wallet, how could that be implemented? It seems that the Aries Cloud Agent does not provide an API for this. The  existing API endpoint `/schemas/created` fetches schema identifiers that are agent oriented only. To use the `/schemas/{schema_id}` endpoint, the business logic would need to know the schema identifier.

Any guidance or pointers how to implement this feature "fetching all schemas from the ledger" would be very welcome.

**Comment by swcurran** [comment]
There is not a way to fetch all the schemas for a given ledger or location — mainly because the typical ledgers we might be using don’t have a way to request such information.  Typically, a developer wanting to reuse a schema would (somehow) find out about it (perhaps in a Governance document about the credential type), get the reference and use it as you indicate above.

We are looking at adding a “read replica” capability for (specifically) Hyperledger Indy that would effectively “cache” the ledger for a given entity, and allow client agents to query it.  That might be where additional features such as you are proposing might be added.

That said, its likely not enough just to fetch all of them. You would know doubt want to query the schemas and return a subset (`give me all the schemas with “given_names” and “photo” attributes`). It gets interesting pretty quickly.

Ideas are welcome, but hard to do directly in ACA-Py without support from the ledger itself.
