### ISSUE TITLE
Bug in Presentation Proposal/Preview?

### ISSUE THREAD

**Issue by domwoe** [hyperledger/aries-cloudagent-python#292]
In [presentation_preview.py](https://github.com/hyperledger/aries-cloudagent-python/blob/1801d4af9234c3c77dd7d54413d8ce5621a0caf5/aries_cloudagent/protocols/present_proof/v1_0/messages/inner/presentation_preview.py)

requested attributes  and predicates are named with literal uuid instead of an unique name

```
proof_req["requested_attributes"][
                    "{}_{}_uuid".format(ord_cred_def_id(cd_id), canon(attr_spec.name))
                ] = {
                    "name": canon(attr_spec.name),
                    "restrictions": [{"cred_def_id": cd_id}],
                    **{
                        "non_revoked": {"from": timestamp, "to": timestamp}
                        for _ in [""]
                        if revo_support
                    },
                }
```

Is this desired or is this a bug?

**Comment by swcurran** [comment]
@sklump - can you please take a look at this?

**Comment by sklump** [comment]
It's just a token. The `uuid` is a historical artifact of the time when these were called uuids instead of referents (circa indy-sdk <1.4-ish). As long as the referent has a unique key within the proof req, it is fine. Since the formatter takes the ordinal of the cred def id within the proof req and the attribute name, it is guaranteed unique.
