### ISSUE TITLE
Combining dependabot PRs strategy

### ISSUE THREAD

**Issue by PatStLouis** [hyperledger/aries-cloudagent-python#3009]
I just did a first run manually, but moving forward it could be beneficial to automate this on a schedule.

I found [this project](https://github.com/marketplace/actions/combine-prs) that does just that. If we think this is a good idea I can have a look at setting this up!

**Comment by WadeBarnes** [comment]
We could group the dependabot updates together into a single PR through the dependabot config, we do that with the GitHub action updates.  The reason we did not start out this way was because we received feedback from the developers that some of the recommendations may not be suitable or work, therefore it was best to keep them separated.

If we find the recommendations work without issue most of the time, we should look into updating the config to combine them into a single PR.

**Comment by PatStLouis** [comment]
So far all of the recommendations were successful at the exception of 1 for the demo and it was a major update. I would be curious about the depth of config dependabot allows, such as excluding major version updates from being grouped since they are the most likely to introduce breaking changes and will come up less frequently. This being said it was fairly easy to see which package was causing the tests to fail based on the logs. 

I agree this sounds like the better approach.

**Comment by jamshale** [comment]
Close for now. If this becomes annoying we can re-address.
