### ISSUE TITLE
Remove deprecated protocols

### ISSUE THREAD

**Issue by PatStLouis** [hyperledger/aries-cloudagent-python#3185]
now that 1.0 is released and following #3184
are we ready to remove the aipv1 protocols (issue-credential / present-proof) from the code base?

implementers using these protocols can continue using the current release.

@dbluhm @jamshale @swcurran ?

**Comment by dbluhm** [comment]
I am in favor of this. The main question I have is whether we just drop it or we move it to a plugin.

For #3184, I opened this PR to the plugin repo: https://github.com/hyperledger/aries-acapy-plugins/pull/925. For a while, I'd been thinking of using the plugins repo as the mechanism for retiring old protocols. But now that we've established LTS releases, I'm actually wondering if we should even bother with turning them into a plugin. There's a maintenance burden to plugins still, as @jamshale can attest to lol. And ripping connections out into a plugin wasn't actually as clean as I'd hoped. I've broken things and to get it working, they'll have to be fixed with new code and new patterns. This adds to the maintenance overhead.

**Comment by dbluhm** [comment]
Is the action menu protocol still used? @swcurran

**Comment by swcurran** [comment]
Interestingly, I have a demo tomorrow from someone using it. So yes.  Let me see what I learn at that meeting.

**Comment by swcurran** [comment]
I don’t like general issues like this that are not actionable.  I would be OK with an issue that says “Document the ways to deprecate protocols” (is that needed?), and issues for proposing specific protocols be deprecated with a `Yes+How+PR` or `No` being the outcome, but something as generic as this issue isn’t really helpful. 

Closing this particular issue (but reopen if you disagree) and please create other issues for direct/actionable issues.
