### ISSUE TITLE
issue-credential protocol needs a touch-up: proposal preview, version

### ISSUE THREAD

**Issue by sklump** [hyperledger/aries-cloudagent-python#329]
Version number is moving to 1.1 to comply with semver. The code base should remove v1.0 lock-in en passant.

The preview of the credential proposal should be optional; neither issuer nor holder should assume its presence.

**Comment by swcurran** [comment]
What is the change that triggers a version change?  Is it in aries-rfcs as a version change?  If it is just that the preview in the credential proposal is optional, that is a clarification, as it was intended that way.  Note that if it is the 0036 change that Keith Smith made, we don't want to support that yet, as it is not part of Aries Interop Profile (AIP) 1.0.0. (3.0.2).

Are you make the change in a way that we continue to support the 1.0 version? If not, we have to do a community-coordinated up date (e.g. pain).  If we are going to be sending out 1.1 messages, we'll have to make sure that others are able to handle that.

**Comment by sklump** [comment]
There are two changes here. One is the version number, and I will do whatever BC likes here. The other is to make the code implement the standard, which always had the preview as optional.

**Comment by sklump** [comment]
I'd like to take out the v1_0/ subdirectory and the V10 prefixes on artifacts, which I put in originally to avoid duplication with the existing v0 implementation (name collisions cause crash on startup). I can do this once aca-py removes v0 code, or at the same time.

**Comment by swcurran** [comment]
OK - as we adopt AIP, and initially AIP 1.0.0 (https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0302-aries-interop-profile#aries-interop-profile-version-100), we should advertise that in ACA-Py, and stick to it. AIPs indicate the specific versions of protocols to support.

For 0036 in particular, AIP 1.0.0 uses this version - https://github.com/hyperledger/aries-rfcs/tree/64e5e55c123b2efaf38f4b0911a71a1c40a7f29d/features/0036-issue-credential

It is the 1.0 version of all the messages.  In that one Proposal and Preview should be optional, so that change should go ahead.

I'm not sure the V1.0 prefixes should come out or not. In future we will likely have to support multiple versions.  What do you think?

**Comment by sklump** [comment]
Maybe keep the V10 prefixes in, but locking versions into the directory structure was a small mistake IMO. It is going to encourage sloppy copy-paste practice.

**Comment by swcurran** [comment]
Your call - you folks you far, far, far better than I. :-)

**Comment by swcurran** [comment]
Note, we can make clarifications in the RFCs without changing the protocol version and change the link in the AIP, if that would help. I notice that the preview being optional is not explicitly stated, but was only was intended to be.

**Comment by sklump** [comment]
It _is_ stated though:
'''
credential_proposal -- an optional JSON-LD object that represents the credential data that Prover wants to receive. It matches the schema of Credential Preview.
'''
I just never got it.

**Comment by swcurran** [comment]
Ah good. I scanned it and missed it 🤔

**Comment by sklump** [comment]
Puzzling evidence: although it is of type preview, it is called proposal, although it is itself a component of the credential proposal message. Historical artifact.

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/347 addresses.
