### ISSUE TITLE
Evaluate effort and impact of implementing 0036 Credential Proposal V1.1

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#341]
Because of the intricacies of the Aries Interop Profile versioning, I'd like to know what the impact would be of adding support for version 1.1 of [credential proposal in 0036](https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential#propose-credential). The change is outlined [here](https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential#11propose-credential). I would assume we would have to make the receipt of that message support the optional parameters, and handle them appropriately. Please confirm or correct my understanding, and the effort and impact of making that change.

Needs also to address this [PR](https://github.com/hyperledger/aries-rfcs/pull/393) to the 0036 RFC.

**Comment by swcurran** [comment]
@andrewwhitehead Can please take a quick look at this issue and reply with a comment that answers my questions?

Thanks

**Comment by sklump** [comment]
The business logic is already in place.

What's left is to change the `PROTOCOL_URI` to read `1.1` instead of `1.0` in `message_types.py`, and/or to change the V10 prefixes all over everything, which prevents duplicate names with the bronto-protocol, then finally to rename the subdirectory (subpackage) from `v1_0` to `v1_1`. I don't know whom that affects though.

Since any v1.0 proposal, other than message type, is a v1.1 proposal, whom does it hurt if we quietly change over on some evening?

**Comment by sklump** [comment]
What I can do is duplicate the v1_0 subpackage into a v1_1 subdirectory, which I'll submit in a PR for evaluation.
