### ISSUE TITLE
Rationalize the logging in ACA-Py

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#438]
While the team building ACA-Py has been pretty good at maintaining the logging, there is some inconsistency in the handling of logging.  This task is to formalize the logging approach across the board, and then to do a pass through the code ensuring that the logging statements match the intention of the approach. 

The first part (formalizing) is likely just creating something like a "logging.md" that outlines how contributors should be doing logging. Even better would be to find and reference (likely in "contributors.md") a well-known Python standard logging approach. Whatever is selected should be reviewed and agreed to by the team.

The second part includes ensuring the logging library is configured appropriately, any non-logging `print` statements are either removed or converted to logging calls, and that all logging is happening at the appropriate level (e.g. debug, warn, error, etc.).

Wrapping up the project will include adding guidance (or CI checks?) for existing and future devs on how they can make sure that the logging remains top notch.

**Comment by nacerix** [comment]
I am interested in working on this issue.

**Comment by swcurran** [comment]
Assigned to you @nacerix -- thanks.  Please let us know if you have any questions.

Please look at the contributor guidelines and especially make note of the need to DCO sign off every commit.  That is a requirement with all Hyperledger repos.  Much worse if you find out about that later. :-)

**Comment by nacerix** [comment]
sure, I will do

**Comment by nacerix** [comment]
Some proposals to start the discussion:
1- Print is not a good idea
2- Use Python standard logging module to:
  - You can control message level and filter out not important ones
  - You can decide where and how to output later
  - Write logging records everywhere with a proper level
3- Write logging record everywhere with appropriate level and configure them later. 
  - What is the appropriate level to use? (to do Add recommendations?)
4- Recommend cascaded logger naming: use __name__ as the logger name
5- Capture exceptions with the traceback
6- Use global logger instead of module level logger.
7- Use JSON or YAML logging configuration over code
8- If logging to a file, prefer rotating file handler
9- Setting level names to avoid typos
10- Performance: Wrap Expensive Calls in a Level Check
11- Performance: Avoid Logging in code that is critical for performance

**Comment by swcurran** [comment]
Definitely agree on 1 :-) - that's one we want to be sure to eliminate.

I think the rest of your points are correct but leave it to the devs to both confirm and add guidance as to what is in place now and what we want to have.

@andrewwhitehead @nrempel -- can the two of you add your $0.02CDN to help kickoff this task?

**Comment by nrempel** [comment]
Thanks for picking this up @nacerix!

I agree with all of your points. We use the python logging module and normally make it available like this: https://github.com/hyperledger/aries-cloudagent-python/blob/master/aries_cloudagent/protocols/present_proof/v1_0/manager.py#L42

We allow setting of log level with a command-line parameter when you start the process but it is also possible to ingest a python logging config .ini file for more complex configuration: https://github.com/hyperledger/aries-cloudagent-python/blob/master/aries_cloudagent/config/logging.py

We use `print()` in a couple places early in the lifecycle of the process. If you can find a clean way to move that to the python logging module, go for it. I think we currently use `print()` any time before our logging config has been loaded.

Let me know if you have any questions!

**Comment by chriamue** [comment]
Dear community, this issue is already closed. Can somebody link a file that documents the log-levels or give an example how to change the default WARNING.
There is a command line parameter called `log-level`, but this seems only to handle `debug`, `info` and `warning`.
Other level fall back to warning.

**Comment by swcurran** [comment]
@chriamue -- I recommend you open a new issue on how to use the `log-level` and anything else need to get logs.  You might try searching in the issues and on rocketchat for previous discussions and add a PR to doc it.  Sorry it's a pain to find.
