### ISSUE TITLE
Update each of the versioned protocols with links in code to respective RFC

### ISSUE THREAD

**Issue by nrempel** [hyperledger/aries-cloudagent-python#472]

**Comment by swcurran** [comment]
@nrempel - please add some detail about where these changes are to be made in ACA-Py?  How do we mechanically apply this.  Would it be possible to have all of the links in a single place?

Also, I note that this is a comment.  I think it would be useful to have this as a data value, so that it could be referenced in code -- specifically in the Swagger API.  As part of reviewing the Swagger API, links could be presented and traversed to get to the RFCs.

I have a script in the aries-rfcs repo that compares what RFC file commit is in the AIP list with what master so that we can tell what needs to be reviewed/updated in the AIP list.  It would be good to use the same technique here - to be able to tell what version we reference here vs. what is the latest in the https://github.com/hyperledger/aries-rfcs repo.

Perhaps, we can start by tagging these with the same versions of the protocols with the AIP 1.0 and then run the script to update them --- regen, diff the result, and for each difference, accept/update code/create issues  to manage the upgrade process.

**Comment by sklump** [comment]
What would you think of putting this into `message_types.py` per version, as (say) `SPEC_URI`? This seems natural and least intrusive to me.

**Comment by sklump** [comment]
Working implementation: https://github.com/hyperledger/aries-cloudagent-python/pull/516

@swcurran could you click on the various links in the tags of the admin API and see that they're correct?
