### ISSUE TITLE
Ability to recognise original issuer of credential when stored?

### ISSUE THREAD

**Issue by james-cohen** [hyperledger/aries-cloudagent-python#478]
When credentials are stored in the wallet there doesn't seem to be a human-interpretable identifier of who originally issued it. This is present in the credential exchange record as the connection_id which can then be cross referenced with 'their_label' in active connections, but this record is purged when the credential is stored.

The public DID of the creator of the schema/credential definition is visible, sure, but say for example you have 2 degree certificates using the same schema in your wallet from separate institutions, how would you recognise which is which if you don't know the public DIDs of each issuer? Is it expected that they include their institution name as a credential attribute or the recipient includes an identifier in the referent when they store it? 

Is it possible to include the connection ID through which the credential was issued as an indirect identifier? for example:

```
{
  "results": [
    {
      "referent": "81717766-61f9-477e-a2c0-80ff619c0a52",
      "attrs": {
        "date": "2018-05-28",
        "timestamp": "1587724529",
        "degree": "Maths",
        "name": "Alice Smith",
        "age": "24"
      },
      "schema_id": "EyYNvC2KuQRup84uaNu9sw:2:degree schema:57.75.53",
      "cred_def_id": "EyYNvC2KuQRup84uaNu9sw:3:CL:860:default",
      "rev_reg_id": null,
      "cred_rev_id": null,
      "origin":
      {
       "connection_id": "fafbf169-00ed-4227-8e2e-5091fa537803",
       "their_label": "FaberCollege"
      }
    }
  ]
}
```

**Comment by sklump** [comment]
The data structure comes from indy-sdk.

If an application want to store supplemental metadata, I think this logic ought to go in the controller.

**Comment by swcurran** [comment]
Interesting question and answer.

For data portability purposes, I think that @james-cohen is correct that this information is needed in the credential.  The community has not spent a lot of time on the portability issue -- other than to make it a required feature of the overall architecture.

I don't think whether Indy supports it or not should not be the driving principle in this case, because credential storage should try to be agnostic to the credential type. That is another topic that will be addressed in Aries in the near future as work on Aries Secure Storage moves forward.

I'd like to raise this issue on the Aries WG call soon (perhaps this week).  @TelegramSam - do you think it's time to start talking about these issues?

**Comment by swcurran** [comment]
[Issue](https://github.com/hyperledger/aries-rfcs/issues/479) opened in the Aries RFCs repo about this. We could also open an issue to track this information in the new Aries Storage repo that is underway -- I'm not sure where that is though.  I don't think we should change the current indy-wallet-based implementation we have now, and as such, for now the only solution is that the controller track it in it's database.

Closing this issue on that basis.
