### ISSUE TITLE
Querying about a schema using its seq# doesn't work.

### ISSUE THREAD

**Issue by Sarangc1203** [hyperledger/aries-cloudagent-python#580]
Querying about a schema using its seq# still doesn't work.
The SwaggerUI doesn't accept an integer input.
I also tried using the curl request:
```bash
curl -X GET "http://__IP__:11021/schemas/42" -H "accept: application/json"
```
It gives me this error:
```bash
{"schema_id": ["Value 42 is not an indy schema identifier"]}
```

_Originally posted by @Sarangc1203 in https://github.com/hyperledger/aries-cloudagent-python/pull/223#issuecomment-647133947_

**Comment by sklump** [comment]
![by-seqno](https://user-images.githubusercontent.com/9336556/85900239-7ce85100-b7cd-11ea-8dee-b9752bdf64d1.png)

It's fine. Try latest master.

**Comment by Sarangc1203** [comment]
Yeah, it's working now. Thanks!

**Comment by jcourt562** [comment]
@sklump So this has been closed, but I think the real issue is that the OpenAPI output from Aca-py is returning "schema_json" NOT "schema" as the field in the response (version 0.5.3). I hit this with the 'typescript-fetch' output from openapi meaning I had to explicitly untype the returned API structure to get at the "schema" object returned in the body.
This is a snippet from the 'json' output when openapi/swagger codegen is run against a running 0.5.3 ACA-py for the schema get operation : 

    "SchemaGetResults" : {
      "type" : "object",
      "properties" : {
        "schema_json" : {
          "$ref" : "#/definitions/Schema"
        }
      }
    },
