### ISSUE TITLE
aca-py - Handle the scenario when the wallet database is not available

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#581]
If the wallet database recycles (as can happen on openshift) the aca-py agent goes into an unrecoverable state.  Every request will error out with a StorageError.

Openshift doesn't recognize that the agent is in a bad state so doesn't restart the service.

Either auto-recover the database connection, or recognize the issue and notify openshift to restart the service.  (Possibly by incorporating a database check in the health check service?)

**Comment by swcurran** [comment]
Cool -- I assume this means that you replicated this?  Obvs, if the ACA-Py instance can recover locally that would be best as we would not lose the in-memory queue of work to be processed. 

Another solution is to cluster the database so that we don't (well, call it rarely) have the issue of the database not being available.  Then we can do best efforts on the ACA-Py side knowing that the scenario is rare.  

On the one hand, that puts a heavier burden on ACA-Py/AVCR deployments in K8s environments -- you need a clustered DB. On the other hand, if you are going to run in a K8s environment, all of your components should be cloud native, including your database.

**Comment by swcurran** [comment]
@ianco can this be closed?

**Comment by ianco** [comment]
yes, closed it
