### ISSUE TITLE
Register Additional Message Handler

### ISSUE THREAD

**Issue by TelegramSam** [hyperledger/aries-cloudagent-python#583]
When writing a plugin, I'd like to register an additional handler for a particular type of message. Currently the architecture first resolves an inbound message to a message type, and the message type designates a single handler. I'd like to register a handler that will also receive the inbound message for processing, but that flow is not currently possible. 

Specifically, I'm working on the toolbox plugin adding a routing module, and I'd like to receive a `RouteQueryResponse` message to a handler within my plugin without interrupting the already supplied message handling. I know the handler doesn't do anything, but I'd like to avoid future conflict when functionality is added.

I know I can override the handling, but is there a cleaner way?

**Comment by swcurran** [comment]
@andrewwhitehead @nrempel

**Comment by nrempel** [comment]
> I'd like to register a handler that will also receive the inbound message for processing, but that flow is not currently possible.

If I understand correctly, you are looking for something like middleware? Basically you want to plug into the lifecycle and read from the message before it reaches its destined handler?

**Comment by TelegramSam** [comment]
No, I want to add an additional handler that operates in addition to the destined handler.

**Comment by swcurran** [comment]
The tricky part of this is whether the extra handler should kick in before, after or instead of the existing handler.  I've built a system before that offered such a flexible mechanism.  The good part is that it covered all possible scenarios and so was very helpful. Bad part was that in the way we did it, the code become horribly convoluted. I suspect in a modern system it could be done in a much cleaner way.

Should we request the full capability with some convention of how to notify ACA-Py of what external handlers should be used for a given deployment?

**Comment by TelegramSam** [comment]
At present, I'd be pretty happy with a way to register a 'secondary' handler that didn't interfere with the operation of the 'primary' handler. If a more generalized solution is desirable, we could discuss a more full solution.

This is inside a plugin, so I'd think the plugin would have a mechanism to register the additional handlers.

**Comment by swcurran** [comment]
@nrempel -- is that enough to know what is needed?  I know you have a ton of knowledge about the handler and were in there recently regarding the minor/major version handling.  My instinct is to do this right and provide a way to have the before/replace/after capabilities, but defer on that detail to others. 

I see two ways to proceed:

- You do a bit now on editing the issue description (the first message) to define the path we want to take and for now we hang a "Help Wanted" flag on this.
- We use this as a holding place for you to think about and them implement when you get a chance (unless someone else takes it)

Let me know what you think.  Sound right, @TelegramSam ?

**Comment by nrempel** [comment]
I think this is a useful feature.

The reason I ask about middleware is because we could offer lifecycle hooks as the message travels through the system which allows you to read or modify the message. This would include the required functionality to effectively run an additional handler (you could bind to the onComplete lifecycle hook or something).

If we just wanted add handlers to existing message types, I'm not sure the best way to do that yet since the handler is coded into the message definition. But something to think about.

**Comment by swcurran** [comment]
Closing this -- reopen if needed.
