### ISSUE TITLE
Update the the handling of Credential Issue records

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#695]
Please update the handling of Credential issue records after the completion of the protocol. Currently, either the record is retained or deleted based on the startup parameters.  Change that to:

1. By default, rewrite the record with minimum data about the issue, keeping at least the RevRegID and CredID needed for revocation, along with some minimal metadata.
2. Add (or keep if it already exists) a startup option to delete the credential issue record entirely.
3. Add (or keep if it already exists) a startup option to retain the full credential issue record.

If it would help, make a required startup option that accepts one of the three options.  E.g. `--issue-cred-record-handling [ minimal | keep | delete ]`

**Comment by swcurran** [comment]
**Question**: Would it be worth allowing the issuer to include an optional, controller defined `holder-id` that is simply stored in the credential issue record.  If the controller DB falls behind the wallet DB, the controller could query for the set of credential issue records, get all the `holder-id` and (perhaps) sync up the issued and revoked record status.

**Question**: If the controller now only has to keep the credential issue record ID, and can use that for revoking, should the credential issue record be updated to record the revocation of an issued credential?

**Question**: Should this issue include an update to the "revoke credential" endpoint to accept either a credential issue record ID OR the RevRegID+CredRevID?

@andrewwhitehead @esune @sklump

**Comment by sklump** [comment]
2: Revocation is not in RFC 36 and so we should be leery of tightly binding it where it does not belong.
3: I hate the idea of using a cred ex id as a revocation crowbar. There is a rev reg id and a cred rev id: this tuple is the identifier purpose-built for revocation. If the controller can store a cred ex id then it can store a (rev reg id, cred rev id). Jam them together and pipe-separate them if you must have 1 thing instead of 1 pair.

**Comment by esune** [comment]
@sklump the issue we are facing (and we are trying to resolve) is that:
- we NEED to have the revocation info (`rev_id` and `rev_reg_id`) in order to be able to revoke a credential
- we want to have a mechanism that allows us to recover when something goes sideways, regardless of whether we are retaining the credential-exchange info or pruning it after issuing a credential, and disregarding what the controller may or may not be doing with that information (having a single point with all the information)
- we DO NOT have any control on the controller, so we are not guaranteed that it will be storing the credential/revocation info
  - for this reason, it is impossible to enforce backups of both agent wallet and controller db and keep them in sync

> re: cred ex records after protocol completion and their stripping down to revocation info, they are no longer cred ex records but revocable credential records.
I agree with you that these new records are something different and therefore should be stored in a different namespace than the standard credential-exchange. However, I think we should keep the information for the non-revocable credentials as well as it provides an easy way for the controller to know whether a credential is revocable or not just by checking whether a `rev_id` and `rev_reg_id` are available for that credential-exchange (instead of having to figure things out by cross-referencing the `cred_def` information with the credential/credex details.

**Question 1:** I don't see the benefit of having this, as it brings us back to having possible out-of-sync issues between controller db and wallet. I believe the slim "credential history" record would have all of the information required by the controller to use with its own logic to sync things up if necessary.

**Question 2:** the way I read this is `should the agent be able to know whether a credential it has issued has since been revoked or not, without having to run a proof?`. If this is what you are asking, we could think of having a `revoked: true | false` flag added to the "credential history" record. This would also provide a way for the controller to know which credentials have been revoked and which haven't, without the need to keep its db in sync and/or requesting proofs to check their status.

**Question 3:** if the credential-exchange is persisted, I like the idea of providing a utility endpoint that looks like `/issue-credential/records/{cred_ex_id}/revoke`. This would be a shorthand to fetching the credex record, pulling the revocation info and posting to the appropriate endpoint. A nice to have.

**Comment by sklump** [comment]
It's a quibble, but I think revoking a credential should go under revocation/, not issue-credential/, because it does not appear in the RFC that the header advertises.

**Comment by esune** [comment]
I am good with that. The endpoint would then be something like `/revocation/{cred_ex_id}/revoke`.
