### ISSUE TITLE
Prover checks if a credential in their wallet is revoked

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#729]
Is there a way to invoke this Indy Node transaction - https://github.com/hyperledger/indy-node/blob/master/docs/source/requests.md#get_revoc_reg_delta - such that a prover could find out if there credential has been revoked? 

Perhaps an ACA-Py Admin API isCredentialRevoked(credential) called by a prover controller that:

- finds the credential in wallet
- determines if it is revocable -- if not trigger event "Not revoked" and exit
- determines the RevRegistry, time of last check (or issue date/time if never checked)
- calls the indy-node function with `from = lastCheckTime` and `to = now()`
- extract the list of revoked credentials returned from the call
- check if the prover's credential ID is in list and if so:
   - update the lastCheckTime, flag the credential as revoked, trigger event "Revoked", and exit
- update the lastCheckTime and trigger event "Not revoked"

Determine if the capability is possible and document how. Once we have that we can decide to proceed or not.

**Comment by sklump** [comment]
Can I take this one instead? It will take me about a day.

**Comment by sklump** [comment]
I can take this if you like. It should take about a day.

I think the to/from/last-check shenanigans are extraneous. Let the ledger retain deltas (single source of truth) and read off cred rev ids revoked.

Alternatively, the prover can always call the issuer's admin API (if the issuer is up), but this is worse because the issuer knows that the prover has checked.

**Comment by ianco** [comment]
I found this function in the indy-sdk, does this do what we need?

https://github.com/hyperledger/indy-sdk/blob/master/libindy/src/api/anoncreds.rs#L2262

I need to experiment with it a bit ...

Theoretically since the holder knows the rev reg id and the index of their credential they should be able to check independently if the credential is revoked (without contacting the issuer).

**Comment by ianco** [comment]
The aca-pi api "GET /present-proof/records/{pres_exch_id}/credentials" returns data in this format:

[{"cred_info": {"referent": "2193127d-88bb-4171-8171-085798a7faa5", "attrs": {"timestamp": "1601334830", "degree": "Maths", "name": "Alice Smith", "age": "24", "date": "2018-05-28"}, "schema_id": "4wR1x7SNe1k3Dq8JsWtGMm:2:degree schema:80.38.38", "cred_def_id": "4wR1x7SNe1k3Dq8JsWtGMm:3:CL:36:default", "rev_reg_id": "4wR1x7SNe1k3Dq8JsWtGMm:4:4wR1x7SNe1k3Dq8JsWtGMm:3:CL:36:default:CL_ACCUM:bab8f5c4-814f-4996-9655-23cc7c6aa533", "cred_rev_id": "1"}, "interval": {"from": null, "to": 1601335170}, "presentation_referents": ["0_degree_uuid", "0_date_uuid", "0_age_GE_uuid", "0_name_uuid"]}]

These values match up with the parameters required in the indy-sdk fn "indy_create_revocation_state()" no?

**Comment by sklump** [comment]
The revocation state creation a step en route to a proof presentation, which we want to avoid. The info is in the delta in its revoked list: take yes for an answer and proceed

**Comment by sklump** [comment]
I'd love to take this one and leave you to focus on the ongoing investigation of postgres record locking vs. concurrent updates. That one is going to wreck the planet, left unchecked.

**Comment by ianco** [comment]
@sklump it's all yours!

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/735
