### ISSUE TITLE
Add test to automate the detection/documentation of Admin API changes

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#742]
@jcourt562 mentioned that he is detecting changes in the Admin API by using the swagger definition to generate a client for the API and then looking for changes from previous generations.  ACA-Py has been updated to make the generated swagger definition predictably ordered to make such comparisons easier.

It would be nice to have such a mechanism added to the repo for detecting expected and unexpected changes to the API.  Have a way to run the process, generate the client and then diff the result with the last known good version of the client.  Ideally, the test would be in the CI/CD pipeline (forcing developer to account for and document their changes), but it could also be just a manual process we run before each release to make sure that the release notes sufficiently document the API changes.

By having the expected result in the repo, we can also provide a URL for a GitHub tag-to-tag comparison of the generated client  code.

**Comment by swcurran** [comment]
@jcourt562 -- interested in helping with this one?  :-)

**Comment by jcourt562** [comment]
I would need to check with my CEO, however its likely we could be interested in helping here with some giveback.

Cheers

John



________________________________

**Comment by jcourt562** [comment]
Let me look into this and see what I can do.

Cheers

John

**Comment by jcourt562** [comment]
Hey Stephen, you can assign this one to me. I have a script (yeah ok its only bash but hey), it runs up the ACA-py docker, and then runs the swagger-cogegen docker image against it to create an openapi.json file, so its not language specific.  We should be able to use that with maybe a little bit of change from what we do afterwards for specific language generation.  One issue is that doing this in the CI/CD only really works (at least we have it working that way) with the "shell" executor since it needs to share the fs for input output.  I might submit it as a manual script for now until I understand your CI/CD a little better.

**Comment by swcurran** [comment]
That works.  Now that we have merged all of the configuration systems for ACA-Py into a unified system (#739 ) we should also have a "usage" run as part of this that we also check for changes on a merge by merge basis.  Don't feel obligated to do that as well, but I assume we'll piggyback on what you do.

@WadeBarnes can help with any CI/CD questions, and can take what you produce to move into CI/CD.

Thanks!

**Comment by sklump** [comment]
bash is way underrated as a scripting language. Minimal external dependencies!
