### ISSUE TITLE
How to create connection with aries-framework-javascript (mediator agent)

### ISSUE THREAD

**Issue by proteche** [hyperledger/aries-cloudagent-python#844]
how can i connect `aries-cloudagent-python` agent to `aries-framework-javascript` mediator.

**Comment by TimoGlastra** [comment]
`aries-framework-javascript` is still in early development. If issues arise they are probably because of problems on the javascript side. So it is best to direct those questions towards the JavaScript framework developers (#aries-javascript channel on https://chat.hyperledger.org). 

If you found a bug you can also open an issue in aries-framework-javascript repo ([hyperledger/aries-framework-javascript](https://github.com))

**Comment by swcurran** [comment]
Closing -- all the components are much richer now. :-)
