### ISSUE TITLE
Integration testing in ACA-Py

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#847]
For adding multi-tenancy to ACA-Py I'm looking into adding integration tests to ACA-Py. Unit tests cover a large part of the codebase, but sometimes specific combinations of features and different workflows can cause ACA-Py to break. Even though the unit tests themselves pass.

I discussed with @ianco and @nodlesh today about how to approach this. 
As AATH does a  lot of things integration tests in ACA-Py should also do, we also discussed how we could maybe (re)use parts of this.

We came to the following:
- Use behave (gherkin syntax) to add tests. 
    - A lot of Hyperledger / Aries projects seem to take this approach (framework-go, aries-agent-test-harness, fabric). 
    - It also allows to reuse certain workflows, making it easy to create new test flows from already existing workflows.
- Do not use the aries-agent-test-harness repo (at least for now) to run tests, but reuse some of the logic already implemented
    - Using AATH to run tests will make it harder to add integration tests to new features in ACA-Py. Instead of adding it to your ACA-Py PR you need to add this to AATH. This can give some chicken-egg scenarios where one of them will most likely break until both are merged
    - AATH is for interoperability testing
- I'll make this a separate PR from the multitenancy work (as it is already getting a quite large PR) and start with recreating the alice/faber demo
- The integration tests will be black box, meaning we send requests, and verify the response states and webhooks. We won't be verifying internal states.
- We'll use a single agent that talks to itself to start with (maybe adding more agents later on).
- Add Github actions pipeline that runs automatically for PRs on master branch

Posting this here for feedback and progress updates

**Comment by swcurran** [comment]
I'm not a big fan of recreating what we have in AATH in ACA-Py, but don't have a lot of time to come up with something better.  A couple of comment/questions though:

- The chicken-and-egg problem is not a big deal if you flag the test that is failing that it is expected to fail.  In my opinion, I would prefer we ran more tests and flagged some as "expected to fail" and then be notified when they pass them, so we can change the expected results.  "Hey, our test run fails because some tests have started to pass!!!"

- I was wondering if this comment "The integration tests will be black box" was an indication that we are doing too much internal checking in AATH?  Should we be backing off some things we are doing in AATH because we are checking too much?

- I am a fan of using Behave and (now) Allure for testing.  Awesome stuff!

**Comment by TimoGlastra** [comment]
> * The chicken-and-egg problem is not a big deal if you flag the test that is failing that it is expected to fail.  In my opinion, I would prefer we ran more tests and flagged some as "expected to fail" and then be notified when they pass them, so we can change the expected results.  "Hey, our test run fails because some tests have started to pass!!!"

In that case the chicken-and-egg problem is resolved. I've worked with external integration tests and it always felt like a burden to maintain and keep in sync (Interoperability tests are different IMO). We're already noticing this with ACA-Py updates breaking AATH startup, needing to add if/else statements based on the ACA-Py version. The same with .NET, where a change in the public API broke AATH. The fix was to update, but now all older versions of the .NET agent can't be tested with AATH anymore.

We need to solve these problems for AATH because we want to test different combinations of agents/versions. But for integration testing it doesn't really seem like we need to solve these problems. We just want to test the current branch and see if everything works as expected (that is my assumption). So besides doing interoperability and protocol compliance testing, AATH now also has to take ACA-Py implementation specific tests into account. Also the backchannel setup adds an extra layer, which makes writing tests more complex.

To add some extra clarity. The idea was not to void all the work done in AATH, I wanted to take it as a starting point and strip all unneeded functionalities not needed for integration testing. But you're definitely right on the fact that we're recreating some parts of AATH in ACA-Py. I'm going to think about it a bit more.

> * I was wondering if this comment "The integration tests will be black box" was an indication that we are doing too much internal checking in AATH?  Should we be backing off some things we are doing in AATH because we are checking too much?

I don't think black box is the correct term. What I meant (and what AATH is also doing with ACA-Py) is that we only make use of public apis. We're using ACA-Py in the same way everyone that uses ACA-Py for their applications is using. We don't 'hook' into the internals of ACA-Py to do custom checks. We validate whether certain input gives us the expected output.

> * I am a fan of using Behave and (now) Allure for testing.  Awesome stuff!

Great. We're all on the same page on this one :)

**Comment by ianco** [comment]
I disagree that we're duplicating AATH here, but in any case I think this is a moot point.

What we want to implement is a set of integration tests that are executed on each PR in the aca-py repository.  We want to be able to test aca-py-specific features, and we want to run on each PR, as opposed to on a schedule (the way AATH is run).  AATH could potentially fulfill these requirements, however we don't want to start building aca-py-specific tests into AATH (it should stay focussed on interoperability testing).

We decided the integration tests should use behave (same as AATH, and in fact this is consistent with how a lot of the HL projects are running integration tests, afgo and fabric are 2 examples) and should be "black box", in the sense that they run an aca-py instance and then run tests by invoking api calls and checking results - this will result in some duplication or reuse of AATH components, since AATH already does this.  However I don't know of a more efficient way to get the aca-py integration tests up & running.

I think we're probably all in agreement on the need for integration tests and approach, and I think it's wise to be careful of "duplication" - we should re-factor AATH *if possible* to use shared (rather than duplicated) code, and be careful that the aca-py integration tests are not just a duplication of tests that are already implemented in AATH.

**Comment by nodlesh** [comment]
One thing that came out of the meeting we had was to regroup after Timo had one or two tests written and reassess the separation from AATH.  I think there is room for different approaches in AATH (eg. a set of acapy integration tests that don't hit the backchannel), however, when doing testing directly against a product that probably won't be used against any other product, it is sometimes wise to keep the tests close to the product code it is testing. The feedback loop is shortened, which, Ian mentions, is key if developers want these tests to tell them they didn't break anything on a per PR basis. We have that problem now, the dev is not aware of the results of the tests on the daily run of AATH, plus the results may show cumulative PRs so narrowing down what broke it is more difficult.

One benefit to having the integration tests in the AATH is that you could mix interop test steps with integration test steps to do things with other types of agents within your integration tests. Not sure if the need for that would arise. 

I do agree with Timo that the version problem, something that does need to be addressed in AATH, is not a concern for product-specific integration tests. However, whatever scheme we decide on to solve that problem, I don't think it would strap a set of integration tests to the solution that you would have to worry about it.  

"Too much checking in AATH"? Geez, I held back a lot. 😎 For the most part, it only checks http response codes and agent states based on RFCs. Not sure how we would determine pass or fail otherwise.

**Comment by swcurran** [comment]
We have integration testing in ACA-Py now (thanks @ianco !!). Closing.
