### ISSUE TITLE
Acme Controller Workshop: Attribute with restrictions cannot be self-attested: 'name'

### ISSUE THREAD

**Issue by ljysdfz** [hyperledger/aries-cloudagent-python#922]
![image](https://user-images.githubusercontent.com/3489980/105635022-d156ca80-5e9b-11eb-9f28-55f4090be29c.png)

As long as I run the "Acme Controller Workshop" demo without starting the Faber demo in the first place, it would appear like above. All necessary code snippets have been stuffed in [acme.py](https://github.com/hyperledger/aries-cloudagent-python/files/5862597/acme.txt).

My steps for re-creating the error:
1. Launch the Acme demo in A terminal.
2. Launch the Alice demo in B terminal.
3. Connect dual peers by copying invitation.
4. Choose the second choice in the panel of Acme.
5. The error breaks out.

Note that if I flip on the Faber demo at first, which suggests following below instructions exactly, the demo routine would go well after all. Weird.
![image](https://user-images.githubusercontent.com/3489980/105635434-be44fa00-5e9d-11eb-8854-ff6ccc0b2dea.png)

**Comment by swcurran** [comment]
Not sure what the issue was. The Acme demo has been updated, so this might have been addressed. Please re-open if appropriate.

**Comment by arminveres** [comment]
This happens on a fresh demo and a custom agent on the first run, but rerunning and re-adding the schema/credentials results in a positive proof... Any specific solution to this?

**Comment by swcurran** [comment]
I don’t really understand what “this” is in your question and what exactly happens when rerunning re-adding.  Could you be more precise on the issue — what you did, what you expected to happen, what did happen.

On the title of the issue — I believe it is correct that the an attribute with restrictions cannot be self-asserted, since it wouldn’t meet the restrictions. I think the only way to use self-attested is to have no restrictions on the request-attribute.
