### ISSUE TITLE
Consistent DIDs in multi-tenancy

### ISSUE THREAD

**Issue by james-cohen** [hyperledger/aries-cloudagent-python#974]
Is there any way of setting the public DID for a tenant in multi-tenancy mode either by using an existing DID and verkey on the ledger or using a seed, as with 'regular' agents?

My experience so far is that every time a new wallet is created, you need to create a new private DID (which seems to be randomised), and then register that to the ledger using the DID and verkey before setting it it to be public. Having the seed based creation process would be helpful for consistency, especially during development where the agent is being destroyed and recreated regularly

**Comment by TimoGlastra** [comment]
Hi @james-cohen,

This is not possible at the moment. A lot of people describe the issue you're describing, especially during development. The only way to create a public DID is the method you described. 

There are plans to add wallet import and export functionality which means you could import a wallet with a specific did stored. The seed is not added because of security reasons, which is of course not a problem for development

**Comment by james-cohen** [comment]
Very valid, the seed security issue is obvious now you mention it. Development fatigue making me wanting to cut corners as usual. Thanks for the quick response

**Comment by MajdT51** [comment]
@TimoGlastra is there any way or tricks to extract only the private key of a Sub-Wallet with a specific did? to be able to use that private key outside Aca Py for other use cases in my application
